<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">
<!-- Generated by PHPExcel - http://www.phpexcel.net -->
<html>
  <head>
	  <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
	  <meta name="author" content="com" />
	  <meta name="company" content="Microsoft Corporation" />
	<style type="text/css">
	  html { font-family:Calibri, Arial, Helvetica, sans-serif; font-size:11pt; background-color:white }
	  table { border-collapse:collapse; page-break-after:always }
	  .gridlines td { border:1px dotted black }
	  .b { text-align:center }
	  .e { text-align:center }
	  .f { text-align:right }
	  .inlineStr { text-align:left }
	  .n { text-align:right }
	  .s { text-align:left }
	  td.style0 { vertical-align:middle; border-bottom:none #000000; border-top:none #000000; border-left:none #000000; border-right:none #000000; color:#000000; font-family:'돋움'; font-size:11pt; background-color:white }
	  td.style1 { vertical-align:middle; border-bottom:none #000000; border-top:3px solid #000000 !important; border-left:3px solid #000000 !important; border-right:none #000000; color:#000000; font-family:'굴림'; font-size:11pt; background-color:white }
	  td.style2 { vertical-align:middle; border-bottom:none #000000; border-top:3px solid #000000 !important; border-left:none #000000; border-right:none #000000; color:#000000; font-family:'굴림'; font-size:12pt; background-color:white }
	  td.style3 { vertical-align:middle; border-bottom:none #000000; border-top:3px solid #000000 !important; border-left:none #000000; border-right:3px solid #000000 !important; color:#000000; font-family:'굴림'; font-size:12pt; background-color:white }
	  td.style4 { vertical-align:middle; border-bottom:none #000000; border-top:none #000000; border-left:3px solid #000000 !important; border-right:none #000000; color:#000000; font-family:'굴림'; font-size:11pt; background-color:white }
	  td.style5 { vertical-align:middle; border-bottom:none #000000; border-top:none #000000; border-left:none #000000; border-right:none #000000; color:#000000; font-family:'굴림'; font-size:12pt; background-color:white }
	  td.style6 { vertical-align:middle; border-bottom:none #000000; border-top:none #000000; border-left:none #000000; border-right:3px solid #000000 !important; color:#000000; font-family:'굴림'; font-size:12pt; background-color:white }
	  td.style7 { vertical-align:middle; text-align:left; padding-left:9px; border-bottom:none #000000; border-top:none #000000; border-left:none #000000; border-right:none #000000; color:#000000; font-family:'굴림'; font-size:12pt; background-color:white }
	  td.style8 { vertical-align:middle; border-bottom:none #000000; border-top:none #000000; border-left:none #000000; border-right:none #000000; text-decoration:underline; color:#000000; font-family:'굴림'; font-size:12pt; background-color:white }
	  td.style9 { vertical-align:middle; text-align:center; border-bottom:1px solid #000000 !important; border-top:1px solid #000000 !important; border-left:1px solid #000000 !important; border-right:1px solid #000000 !important; color:#000000; font-family:'굴림'; font-size:12pt; background-color:white }
	  td.style10 { vertical-align:middle; text-align:center; border-bottom:1px solid #000000 !important; border-top:1px solid #000000 !important; border-left:1px solid #000000 !important; border-right:1px solid #000000 !important; color:#000000; font-family:'돋움'; font-size:11pt; background-color:white }
	  td.style11 { vertical-align:middle; text-align:center; border-bottom:1px solid #000000 !important; border-top:1px solid #000000 !important; border-left:1px solid #000000 !important; border-right:1px solid #000000 !important; color:#000000; font-family:'굴림'; font-size:12pt; background-color:white }
	  td.style12 { vertical-align:middle; text-align:center; border-bottom:1px solid #000000 !important; border-top:1px solid #000000 !important; border-left:1px solid #000000 !important; border-right:1px solid #000000 !important; color:#000000; font-family:'굴림'; font-size:12pt; background-color:white }
	  td.style13 { vertical-align:middle; text-align:center; border-bottom:1px solid #000000 !important; border-top:1px solid #000000 !important; border-left:1px solid #000000 !important; border-right:1px solid #000000 !important; color:#000000; font-family:'굴림'; font-size:12pt; background-color:white }
	  td.style14 { vertical-align:middle; border-bottom:none #000000; border-top:1px solid #000000 !important; border-left:1px solid #000000 !important; border-right:1px solid #000000 !important; color:#000000; font-family:'돋움'; font-size:11pt; background-color:white }
	  td.style15 { vertical-align:middle; text-align:center; border-bottom:none #000000; border-top:none #000000; border-left:none #000000; border-right:none #000000; color:#000000; font-family:'굴림'; font-size:12pt; background-color:white }
	  td.style16 { vertical-align:middle; border-bottom:none #000000; border-top:none #000000; border-left:none #000000; border-right:none #000000; font-weight:bold; color:#FF0000; font-family:'굴림'; font-size:12pt; background-color:white }
	  td.style17 { vertical-align:middle; border-bottom:none #000000; border-top:none #000000; border-left:none #000000; border-right:none #000000; font-weight:bold; color:#FF0000; font-family:'굴림'; font-size:12pt; background-color:white }
	  td.style18 { vertical-align:middle; border-bottom:none #000000; border-top:none #000000; border-left:none #000000; border-right:none #000000; color:#FF0000; font-family:'굴림'; font-size:12pt; background-color:white }
	  td.style19 { vertical-align:middle; border-bottom:3px solid #000000 !important; border-top:none #000000; border-left:3px solid #000000 !important; border-right:none #000000; color:#000000; font-family:'굴림'; font-size:11pt; background-color:white }
	  td.style20 { vertical-align:middle; border-bottom:3px solid #000000 !important; border-top:none #000000; border-left:none #000000; border-right:none #000000; color:#000000; font-family:'굴림'; font-size:12pt; background-color:white }
	  td.style21 { vertical-align:middle; border-bottom:3px solid #000000 !important; border-top:none #000000; border-left:none #000000; border-right:3px solid #000000 !important; color:#000000; font-family:'굴림'; font-size:12pt; background-color:white }
	  td.style22 { vertical-align:top; border-bottom:1px dotted #000000 !important; border-top:3px solid #000000 !important; border-left:none #000000; border-right:none #000000; font-weight:bold; color:#000000; font-family:'굴림'; font-size:10pt; background-color:white }
	  td.style23 { vertical-align:middle; border-bottom:1px dotted #000000 !important; border-top:3px solid #000000 !important; border-left:none #000000; border-right:none #000000; font-weight:bold; color:#000000; font-family:'굴림'; font-size:10pt; background-color:white }
	  td.style24 { vertical-align:top; text-align:right; padding-right:0px; border-bottom:1px dotted #000000 !important; border-top:3px solid #000000 !important; border-left:none #000000; border-right:none #000000; font-weight:bold; color:#000000; font-family:'굴림'; font-size:10pt; background-color:white }
	  td.style25 { vertical-align:middle; border-bottom:none #000000; border-top:none #000000; border-left:none #000000; border-right:none #000000; color:#000000; font-family:'굴림'; font-size:10pt; background-color:white }
	  td.style26 { vertical-align:middle; border-bottom:none #000000; border-top:2px solid #000000 !important; border-left:2px solid #000000 !important; border-right:none #000000; color:#000000; font-family:'굴림'; font-size:11pt; background-color:white }
	  td.style27 { vertical-align:middle; border-bottom:none #000000; border-top:2px solid #000000 !important; border-left:none #000000; border-right:none #000000; color:#000000; font-family:'굴림'; font-size:12pt; background-color:white }
	  td.style28 { vertical-align:middle; border-bottom:none #000000; border-top:2px solid #000000 !important; border-left:none #000000; border-right:2px solid #000000 !important; color:#000000; font-family:'굴림'; font-size:12pt; background-color:white }
	  td.style29 { vertical-align:middle; border-bottom:none #000000; border-top:none #000000; border-left:2px solid #000000 !important; border-right:none #000000; color:#000000; font-family:'굴림'; font-size:11pt; background-color:white }
	  td.style30 { vertical-align:middle; border-bottom:none #000000; border-top:none #000000; border-left:none #000000; border-right:none #000000; color:#000000; font-family:'굴림'; font-size:12pt; background-color:white }
	  td.style31 { vertical-align:middle; border-bottom:none #000000; border-top:none #000000; border-left:none #000000; border-right:2px solid #000000 !important; color:#000000; font-family:'굴림'; font-size:12pt; background-color:white }
	  td.style32 { vertical-align:middle; border-bottom:none #000000; border-top:none #000000; border-left:none #000000; border-right:none #000000; color:#000000; font-family:'굴림'; font-size:12pt; background-color:white }
	  td.style33 { vertical-align:middle; border-bottom:none #000000; border-top:none #000000; border-left:none #000000; border-right:none #000000; color:#000000; font-family:'굴림'; font-size:12pt; background-color:white }
	  td.style34 { vertical-align:middle; border-bottom:none #000000; border-top:none #000000; border-left:none #000000; border-right:none #000000; color:#000000; font-family:'굴림'; font-size:23pt; background-color:white }
	  td.style35 { vertical-align:middle; text-align:left; padding-left:0px; border-bottom:none #000000; border-top:none #000000; border-left:none #000000; border-right:none #000000; color:#000000; font-family:'굴림'; font-size:23pt; background-color:white }
	  td.style36 { vertical-align:middle; text-align:center; border-bottom:none #000000; border-top:none #000000; border-left:none #000000; border-right:none #000000; color:#000000; font-family:'굴림'; font-size:12pt; background-color:white }
	  td.style37 { vertical-align:middle; text-align:center; border-bottom:none #000000; border-top:none #000000; border-left:none #000000; border-right:none #000000; color:#000000; font-family:'굴림'; font-size:12pt; background-color:white }
	  td.style38 { vertical-align:middle; border-bottom:none #000000; border-top:none #000000; border-left:none #000000; border-right:none #000000; color:#000000; font-family:'돋움'; font-size:11pt; background-color:white }
	  td.style39 { vertical-align:middle; text-align:left; padding-left:9px; border-bottom:none #000000; border-top:none #000000; border-left:none #000000; border-right:none #000000; color:#000000; font-family:'굴림'; font-size:23pt; background-color:white }
	  td.style40 { vertical-align:middle; border-bottom:none #000000; border-top:none #000000; border-left:none #000000; border-right:none #000000; color:#000000; font-family:'굴림'; font-size:23pt; background-color:white }
	  td.style41 { vertical-align:middle; border-bottom:none #000000; border-top:none #000000; border-left:none #000000; border-right:none #000000; color:#000000; font-family:'굴림'; font-size:11pt; background-color:white }
	  td.style42 { vertical-align:bottom; border-bottom:none #000000; border-top:none #000000; border-left:none #000000; border-right:none #000000; color:#000000; font-family:'굴림'; font-size:12pt; background-color:white }
	  td.style43 { vertical-align:bottom; text-align:left; padding-left:9px; border-bottom:none #000000; border-top:none #000000; border-left:none #000000; border-right:none #000000; font-weight:bold; color:#000000; font-family:'굴림'; font-size:12pt; background-color:white }
	  td.style44 { vertical-align:middle; border-bottom:none #000000; border-top:none #000000; border-left:none #000000; border-right:none #000000; color:#000000; font-family:'굴림'; font-size:12pt; background-color:white }
	  td.style45 { vertical-align:bottom; text-align:left; padding-left:9px; border-bottom:none #000000; border-top:none #000000; border-left:none #000000; border-right:none #000000; color:#000000; font-family:'굴림'; font-size:12pt; background-color:white }
	  td.style46 { vertical-align:bottom; text-align:left; padding-left:0px; border-bottom:none #000000; border-top:none #000000; border-left:none #000000; border-right:none #000000; color:#000000; font-family:'굴림'; font-size:12pt; background-color:white }
	  td.style47 { vertical-align:top; text-align:left; padding-left:9px; border-bottom:none #000000; border-top:none #000000; border-left:none #000000; border-right:none #000000; color:#000000; font-family:'굴림'; font-size:12pt; background-color:white }
	  td.style48 { vertical-align:top; text-align:left; padding-left:0px; border-bottom:none #000000; border-top:none #000000; border-left:none #000000; border-right:none #000000; color:#000000; font-family:'굴림'; font-size:12pt; background-color:white }
	  td.style49 { vertical-align:middle; border-bottom:2px solid #000000 !important; border-top:none #000000; border-left:2px solid #000000 !important; border-right:none #000000; color:#000000; font-family:'굴림'; font-size:11pt; background-color:white }
	  td.style50 { vertical-align:middle; border-bottom:2px solid #000000 !important; border-top:none #000000; border-left:none #000000; border-right:none #000000; color:#000000; font-family:'굴림'; font-size:12pt; background-color:white }
	  td.style51 { vertical-align:bottom; text-align:left; padding-left:9px; border-bottom:2px solid #000000 !important; border-top:none #000000; border-left:none #000000; border-right:none #000000; color:#000000; font-family:'굴림'; font-size:12pt; background-color:white }
	  td.style52 { vertical-align:bottom; text-align:left; padding-left:0px; border-bottom:2px solid #000000 !important; border-top:none #000000; border-left:none #000000; border-right:none #000000; color:#000000; font-family:'굴림'; font-size:12pt; background-color:white }
	  td.style53 { vertical-align:middle; border-bottom:2px solid #000000 !important; border-top:none #000000; border-left:none #000000; border-right:2px solid #000000 !important; color:#000000; font-family:'굴림'; font-size:12pt; background-color:white }
	  td.style54 { vertical-align:middle; text-align:center; border-bottom:none #000000; border-top:none #000000; border-left:none #000000; border-right:none #000000; font-weight:bold; color:#000000; font-family:'굴림'; font-size:26pt; background-color:white }
	  td.style55 { vertical-align:middle; text-align:left; padding-left:9px; border-bottom:none #000000; border-top:none #000000; border-left:none #000000; border-right:none #000000; color:#000000; font-family:'굴림'; font-size:23pt; background-color:white }
	  td.style56 { vertical-align:middle; text-align:center; border-bottom:none #000000; border-top:none #000000; border-left:none #000000; border-right:none #000000; color:#000000; font-family:'굴림'; font-size:23pt; background-color:white }
	  td.style57 { vertical-align:middle; text-align:left; padding-left:0px; border-bottom:none #000000; border-top:none #000000; border-left:none #000000; border-right:none #000000; color:#FF0000; font-family:'굴림'; font-size:12pt; background-color:white }
	  td.style58 { vertical-align:middle; text-align:left; padding-left:0px; border-bottom:none #000000; border-top:none #000000; border-left:none #000000; border-right:none #000000; color:#000000; font-family:'굴림'; font-size:12pt; background-color:white }
	  td.style59 { vertical-align:middle; text-align:left; padding-left:0px; border-bottom:none #000000; border-top:none #000000; border-left:none #000000; border-right:none #000000; color:#000000; font-family:'굴림'; font-size:12pt; background-color:white }
	  td.style60 { vertical-align:middle; text-align:center; border-bottom:1px solid #000000 !important; border-top:1px solid #000000 !important; border-left:1px solid #000000 !important; border-right:none #000000; color:#000000; font-family:'굴림'; font-size:12pt; background-color:white }
	  td.style61 { vertical-align:middle; text-align:center; border-bottom:1px solid #000000 !important; border-top:1px solid #000000 !important; border-left:none #000000; border-right:1px solid #000000 !important; color:#000000; font-family:'굴림'; font-size:12pt; background-color:white }
	  td.style62 { vertical-align:middle; text-align:center; border-bottom:1px solid #000000 !important; border-top:1px solid #000000 !important; border-left:1px solid #000000 !important; border-right:none #000000; color:#000000; font-family:'굴림'; font-size:11pt; background-color:white }
	  td.style63 { vertical-align:middle; text-align:center; border-bottom:1px solid #000000 !important; border-top:1px solid #000000 !important; border-left:none #000000; border-right:none #000000; color:#000000; font-family:'굴림'; font-size:11pt; background-color:white }
	  td.style64 { vertical-align:middle; text-align:center; border-bottom:1px solid #000000 !important; border-top:1px solid #000000 !important; border-left:none #000000; border-right:1px solid #000000 !important; color:#000000; font-family:'굴림'; font-size:11pt; background-color:white }
	  table.sheet0 col.col0 { width:8.13333324pt }
	  table.sheet0 col.col1 { width:27.1111108pt }
	  table.sheet0 col.col2 { width:66.42222146pt }
	  table.sheet0 col.col3 { width:42pt }
	  table.sheet0 col.col4 { width:59.64444376pt }
	  table.sheet0 col.col5 { width:72.52222139pt }
	  table.sheet0 col.col6 { width:71.84444362pt }
	  table.sheet0 col.col7 { width:57.61111045pt }
	  table.sheet0 col.col8 { width:6.7777777pt }
	  table.sheet0 col.col9 { width:8.13333324pt }
	  table.sheet0 col.col10 { width:72.52222139pt }
	  table.sheet0 col.col11 { width:71.84444362pt }
	  table.sheet0 tr { height:15pt }
	  table.sheet0 tr.row0 { height:21.95pt }
	  table.sheet0 tr.row1 { height:21.95pt }
	  table.sheet0 tr.row2 { height:21.95pt }
	  table.sheet0 tr.row3 { height:21.75pt }
	  table.sheet0 tr.row4 { height:10.9pt }
	  table.sheet0 tr.row5 { height:21.95pt }
	  table.sheet0 tr.row6 { height:21.95pt }
	  table.sheet0 tr.row7 { height:21.95pt }
	  table.sheet0 tr.row8 { height:21.95pt }
	  table.sheet0 tr.row9 { height:21.95pt }
	  table.sheet0 tr.row10 { height:21.95pt }
	  table.sheet0 tr.row11 { height:21.75pt }
	  table.sheet0 tr.row12 { height:21.95pt }
	  table.sheet0 tr.row13 { height:21.95pt }
	  table.sheet0 tr.row14 { height:21.95pt }
	  table.sheet0 tr.row15 { height:21.95pt }
	  table.sheet0 tr.row16 { height:21.95pt }
	  table.sheet0 tr.row17 { height:21.95pt }
	  table.sheet0 tr.row18 { height:26.25pt }
	  table.sheet0 tr.row19 { height:26.25pt }
	  table.sheet0 tr.row20 { height:21.95pt }
	  table.sheet0 tr.row21 { height:21.95pt }
	  table.sheet0 tr.row22 { height:21.95pt }
	  table.sheet0 tr.row23 { height:36pt }
	  table.sheet0 tr.row24 { height:36pt }
	  table.sheet0 tr.row25 { height:36pt }
	  table.sheet0 tr.row26 { height:14.25pt }
	  table.sheet0 tr.row27 { height:14.25pt }
	  table.sheet0 tr.row28 { height:36pt }
	  table.sheet0 tr.row29 { height:36pt }
	  table.sheet0 tr.row30 { height:36pt }
	  table.sheet0 tr.row31 { height:21.95pt }
	  table.sheet0 tr.row32 { height:21.95pt }
	  table.sheet0 tr.row33 { height:21.95pt }
	</style>
  </head>

  <body>
<style>
@page { left-margin: 0.35433070866142in; right-margin: 0.31496062992126in; top-margin: 0.39370078740157in; bottom-margin: 0in; }
body { left-margin: 0.35433070866142in; right-margin: 0.31496062992126in; top-margin: 0.39370078740157in; bottom-margin: 0in; }
</style>
	<table border="0" cellpadding="0" cellspacing="0" id="sheet0" class="sheet0">
		<col class="col0">
		<col class="col1">
		<col class="col2">
		<col class="col3">
		<col class="col4">
		<col class="col5">
		<col class="col6">
		<col class="col7">
		<col class="col8">
		<col class="col9">
		<col class="col10">
		<col class="col11">
		<tbody>
		  <tr class="row0">
			<td class="column0 style1 null"></td>
			<td class="column1 style2 null"></td>
			<td class="column2 style2 null"></td>
			<td class="column3 style2 null"></td>
			<td class="column4 style2 null"></td>
			<td class="column5 style2 null"></td>
			<td class="column6 style2 null"></td>
			<td class="column7 style2 null"></td>
			<td class="column8 style3 null"></td>
			<td class="column9">&nbsp;</td>
			<td class="column10">&nbsp;</td>
			<td class="column11">&nbsp;</td>
		  </tr>
		  <tr class="row1">
			<td class="column0 style4 null"></td>
			<td class="column1 style5 s">청구 부서 : 영업팀</td>
			<td class="column2 style5 null"></td>
			<td class="column3 style5 null"></td>
			<td class="column4 style54 s style54" colspan="2" rowspan="2">출고 전표</td>
			<td class="column6 style57 n style57" colspan="2">41736</td>
			<td class="column8 style6 null"></td>
			<td class="column9">&nbsp;</td>
			<td class="column10">&nbsp;</td>
			<td class="column11">&nbsp;</td>
		  </tr>
		  <tr class="row2">
			<td class="column0 style4 null"></td>
			<td class="column1 style58 f style58" colspan="3">청구 번호 : SWD-140321-7</td>
			<td class="column6 style59 f style59" colspan="2">41736</td>
			<td class="column8 style6 null"></td>
			<td class="column9">&nbsp;</td>
			<td class="column10">&nbsp;</td>
			<td class="column11">&nbsp;</td>
		  </tr>
		  <tr class="row3">
			<td class="column0 style4 null"></td>
			<td class="column1 style5 s">Buyer: </td>
			<td class="column2 style7 s">Ladkani</td>
			<td class="column3 style5 null"></td>
			<td class="column4 style5 null"></td>
			<td class="column5 style5 null"></td>
			<td class="column6 style5 null"></td>
			<td class="column7 style5 null"></td>
			<td class="column8 style6 null"></td>
			<td class="column9">&nbsp;</td>
			<td class="column10">&nbsp;</td>
			<td class="column11">&nbsp;</td>
		  </tr>
		  <tr class="row4">
			<td class="column0 style4 null"></td>
			<td class="column1 style8 null"></td>
			<td class="column2 style5 null"></td>
			<td class="column3 style5 null"></td>
			<td class="column4 style5 null"></td>
			<td class="column5 style5 null"></td>
			<td class="column6 style5 null"></td>
			<td class="column7 style5 null"></td>
			<td class="column8 style6 null"></td>
			<td class="column9">&nbsp;</td>
			<td class="column10">&nbsp;</td>
			<td class="column11">&nbsp;</td>
		  </tr>
		  <tr class="row5">
			<td class="column0 style4 null"></td>
			<td class="column1 style9 s">번호</td>
			<td class="column2 style9 s">Model name </td>
			<td class="column3 style9 s">출고수량</td>
			<td class="column4 style9 s">PI NO</td>
			<td class="column5 style9 s">생산의뢰서 NO. </td>
			<td class="column6 style9 s">생산의뢰서 잔량</td>
			<td class="column7 style9 s">비고</td>
			<td class="column8 style6 null"></td>
			<td class="column9">&nbsp;</td>
			<td class="column10">&nbsp;</td>
			<td class="column11">&nbsp;</td>
		  </tr>
		  <tr class="row6">
			<td class="column0 style4 null"></td>
			<td class="column1 style9 n">1</td>
			<td class="column2 style10 s">SB-9RL</td>
			<td class="column3 style9 n">40</td>
			<td class="column4 style11 n">PI-140321-7</td>
			<td class="column5 style12 n">SWM-1403-51</td>
			<td class="column6 style13 n">0</td>
			<td class="column7 style14 null"></td>
			<td class="column8 style6 null"></td>
			<td class="column9">&nbsp;</td>
			<td class="column10">&nbsp;</td>
			<td class="column11">&nbsp;</td>
		  </tr>
		  <tr class="row7">
			<td class="column0 style4 null"></td>
			<td class="column1 style9 n">2</td>
			<td class="column2 style10 null"></td>
			<td class="column3 style9 null"></td>
			<td class="column4 style11 null"></td>
			<td class="column5 style12 null"></td>
			<td class="column6 style13 null"></td>
			<td class="column7 style9 null"></td>
			<td class="column8 style6 null"></td>
			<td class="column9">&nbsp;</td>
			<td class="column10">&nbsp;</td>
			<td class="column11">&nbsp;</td>
		  </tr>
		  <tr class="row8">
			<td class="column0 style4 null"></td>
			<td class="column1 style9 n">3</td>
			<td class="column2 style10 null"></td>
			<td class="column3 style9 null"></td>
			<td class="column4 style11 null"></td>
			<td class="column5 style13 null"></td>
			<td class="column6 style13 null"></td>
			<td class="column7 style14 null"></td>
			<td class="column8 style6 null"></td>
			<td class="column9">&nbsp;</td>
			<td class="column10">&nbsp;</td>
			<td class="column11">&nbsp;</td>
		  </tr>
		  <tr class="row9">
			<td class="column0 style4 null"></td>
			<td class="column1 style9 n">4</td>
			<td class="column2 style10 null"></td>
			<td class="column3 style9 null"></td>
			<td class="column4 style11 null"></td>
			<td class="column5 style13 null"></td>
			<td class="column6 style13 null"></td>
			<td class="column7 style9 null"></td>
			<td class="column8 style6 null"></td>
			<td class="column9">&nbsp;</td>
			<td class="column10">&nbsp;</td>
			<td class="column11">&nbsp;</td>
		  </tr>
		  <tr class="row10">
			<td class="column0 style4 null"></td>
			<td class="column1 style60 s style61" colspan="2">총 수량</td>
			<td class="column3 style9 f">40</td>
			<td class="column4 style62 null style64" colspan="4"></td>
			<td class="column8 style6 null"></td>
			<td class="column9">&nbsp;</td>
			<td class="column10">&nbsp;</td>
			<td class="column11">&nbsp;</td>
		  </tr>
		  <tr class="row11">
			<td class="column0 style4 null"></td>
			<td class="column1 style15 null"></td>
			<td class="column2 style15 null"></td>
			<td class="column3 style15 null"></td>
			<td class="column4 style15 null"></td>
			<td class="column5 style15 null"></td>
			<td class="column6 style15 null"></td>
			<td class="column7 style15 null"></td>
			<td class="column8 style6 null"></td>
			<td class="column9">&nbsp;</td>
			<td class="column10">&nbsp;</td>
			<td class="column11">&nbsp;</td>
		  </tr>
		  <tr class="row12">
			<td class="column0 style4 null"></td>
			<td class="column1 style5 null"></td>
			<td class="column2 style5 null"></td>
			<td class="column3 style5 null"></td>
			<td class="column4 style5 null"></td>
			<td class="column5 style16 null"></td>
			<td class="column6 style5 null"></td>
			<td class="column7 style5 null"></td>
			<td class="column8 style6 null"></td>
			<td class="column9">&nbsp;</td>
			<td class="column10">&nbsp;</td>
			<td class="column11">&nbsp;</td>
		  </tr>
		  <tr class="row13">
			<td class="column0 style4 null"></td>
			<td class="column1 style5 null"></td>
			<td class="column2 style5 null"></td>
			<td class="column3 style5 null"></td>
			<td class="column4 style5 null"></td>
			<td class="column5 style17 null"></td>
			<td class="column6 style5 null"></td>
			<td class="column7 style5 null"></td>
			<td class="column8 style6 null"></td>
			<td class="column9">&nbsp;</td>
			<td class="column10">&nbsp;</td>
			<td class="column11">&nbsp;</td>
		  </tr>
		  <tr class="row14">
			<td class="column0 style4 null"></td>
			<td class="column1 style5 null"></td>
			<td class="column2 style5 null"></td>
			<td class="column3 style5 null"></td>
			<td class="column4 style5 null"></td>
			<td class="column5 style18 null"></td>
			<td class="column6 style5 null"></td>
			<td class="column7 style5 null"></td>
			<td class="column8 style6 null"></td>
			<td class="column9">&nbsp;</td>
			<td class="column10">&nbsp;</td>
			<td class="column11">&nbsp;</td>
		  </tr>
		  <tr class="row15">
			<td class="column0 style4 null"></td>
			<td class="column1 style5 null"></td>
			<td class="column2 style5 null"></td>
			<td class="column3 style5 null"></td>
			<td class="column4 style5 null"></td>
			<td class="column5 style5 null"></td>
			<td class="column6 style5 null">
<div style="position: relative;"><img style="position: absolute; z-index: 1; left: 86px; top: 2px; width: 147px; height: 44px;" src="zip://D:\dev\php\web\sbm\sbm.dealer\application\views\test\docs_02.xlsx#xl/media/image1.jpeg" border="0" /></div></td>
			<td class="column7 style5 null"></td>
			<td class="column8 style6 null"></td>
			<td class="column9">&nbsp;</td>
			<td class="column10">&nbsp;</td>
			<td class="column11">&nbsp;</td>
		  </tr>
		  <tr class="row16">
			<td class="column0 style4 null"></td>
			<td class="column1 style5 null"></td>
			<td class="column2 style5 null"></td>
			<td class="column3 style5 null"></td>
			<td class="column4 style5 null"></td>
			<td class="column5 style5 null"></td>
			<td class="column6 style5 null"></td>
			<td class="column7 style5 null"></td>
			<td class="column8 style6 null"></td>
			<td class="column9">&nbsp;</td>
			<td class="column10">&nbsp;</td>
			<td class="column11">&nbsp;</td>
		  </tr>
		  <tr class="row17">
			<td class="column0 style19 null"></td>
			<td class="column1 style20 null"></td>
			<td class="column2 style20 null"></td>
			<td class="column3 style20 null"></td>
			<td class="column4 style20 null"></td>
			<td class="column5 style20 null"></td>
			<td class="column6 style20 null"></td>
			<td class="column7 style20 null"></td>
			<td class="column8 style21 null"></td>
			<td class="column9">&nbsp;</td>
			<td class="column10">&nbsp;</td>
			<td class="column11">&nbsp;</td>
		  </tr>
		  <tr class="row18">
			<td class="column0 style22 s">SBM-공통-P-708-01</td>
			<td class="column1 style23 null"></td>
			<td class="column2 style23 null"></td>
			<td class="column3 style23 null"></td>
			<td class="column4 style24 s">㈜에스비엠</td>
			<td class="column5 style23 null"></td>
			<td class="column6 style23 null">
<div style="position: relative;"><img style="position: absolute; z-index: 1; left: 86px; top: 0px; width: 147px; height: 0px;" src="zip://D:\dev\php\web\sbm\sbm.dealer\application\views\test\docs_02.xlsx#xl/media/image2.jpeg" border="0" /></div>
<div style="position: relative;"><img style="position: absolute; z-index: 1; left: 86px; top: 0px; width: 147px; height: 0px;" src="zip://D:\dev\php\web\sbm\sbm.dealer\application\views\test\docs_02.xlsx#xl/media/image2.jpeg" border="0" /></div>
<div style="position: relative;"><img style="position: absolute; z-index: 1; left: 86px; top: 0px; width: 147px; height: 0px;" src="zip://D:\dev\php\web\sbm\sbm.dealer\application\views\test\docs_02.xlsx#xl/media/image2.jpeg" border="0" /></div>
<div style="position: relative;"><img style="position: absolute; z-index: 1; left: 86px; top: 0px; width: 147px; height: 0px;" src="zip://D:\dev\php\web\sbm\sbm.dealer\application\views\test\docs_02.xlsx#xl/media/image2.jpeg" border="0" /></div>
<div style="position: relative;"><img style="position: absolute; z-index: 1; left: 86px; top: 0px; width: 147px; height: 0px;" src="zip://D:\dev\php\web\sbm\sbm.dealer\application\views\test\docs_02.xlsx#xl/media/image2.jpeg" border="0" /></div></td>
			<td class="column7 style23 null"></td>
			<td class="column8 style24 s">A4(210 X297mm)</td>
			<td class="column9">&nbsp;</td>
			<td class="column10">&nbsp;</td>
			<td class="column11">&nbsp;</td>
		  </tr>
		  <tr class="row19">
			<td class="column0">&nbsp;</td>
			<td class="column1">&nbsp;</td>
			<td class="column2">&nbsp;</td>
			<td class="column3">&nbsp;</td>
			<td class="column4">&nbsp;</td>
			<td class="column5">&nbsp;</td>
			<td class="column6">&nbsp;</td>
			<td class="column7">&nbsp;</td>
			<td class="column8">&nbsp;</td>
			<td class="column9">&nbsp;</td>
			<td class="column10">&nbsp;</td>
			<td class="column11">&nbsp;</td>
		  </tr>
		  <tr class="row20">
			<td class="column0 style26 null"></td>
			<td class="column1 style27 null"></td>
			<td class="column2 style27 null"></td>
			<td class="column3 style27 null"></td>
			<td class="column4 style27 null"></td>
			<td class="column5 style27 null"></td>
			<td class="column6 style27 null"></td>
			<td class="column7 style27 null"></td>
			<td class="column8 style28 null"></td>
			<td class="column9">&nbsp;</td>
			<td class="column10">&nbsp;</td>
			<td class="column11">&nbsp;</td>
		  </tr>
		  <tr class="row21">
			<td class="column0 style29 null"></td>
			<td class="column1 style5 null"></td>
			<td class="column2 style5 null"></td>
			<td class="column3 style5 null"></td>
			<td class="column4 style54 s style54" colspan="2" rowspan="2">인수확인증</td>
			<td class="column6 style30 null">
<div style="position: relative;"><img style="position: absolute; z-index: 1; left: 84px; top: 2px; width: 147px; height: 44px;" src="zip://D:\dev\php\web\sbm\sbm.dealer\application\views\test\docs_02.xlsx#xl/media/image1.jpeg" border="0" /></div></td>
			<td class="column7 style30 null"></td>
			<td class="column8 style31 null"></td>
			<td class="column9">&nbsp;</td>
			<td class="column10">&nbsp;</td>
			<td class="column11">&nbsp;</td>
		  </tr>
		  <tr class="row22">
			<td class="column0 style29 null"></td>
			<td class="column1 style32 null"></td>
			<td class="column2 style32 null"></td>
			<td class="column3 style32 null"></td>
			<td class="column6 style33 null"></td>
			<td class="column7 style33 null"></td>
			<td class="column8 style31 null"></td>
			<td class="column9">&nbsp;</td>
			<td class="column10">&nbsp;</td>
			<td class="column11">&nbsp;</td>
		  </tr>
		  <tr class="row23">
			<td class="column0 style29 null"></td>
			<td class="column1 style5 null"></td>
			<td class="column2 style34 s">인수차량번호:</td>
			<td class="column3 style5 null"></td>
			<td class="column4 style5 null"></td>
			<td class="column5 style5 null"></td>
			<td class="column6 style5 null"></td>
			<td class="column7 style5 null"></td>
			<td class="column8 style31 null"></td>
			<td class="column9">&nbsp;</td>
			<td class="column10">&nbsp;</td>
			<td class="column11">&nbsp;</td>
		  </tr>
		  <tr class="row24">
			<td class="column0 style29 null"></td>
			<td class="column1 style8 null"></td>
			<td class="column2 style34 s">인    수     인:</td>
			<td class="column3 style5 null"></td>
			<td class="column4 style5 null"></td>
			<td class="column5 style5 null"></td>
			<td class="column6 style5 null"></td>
			<td class="column7 style5 null"></td>
			<td class="column8 style31 null"></td>
			<td class="column9">&nbsp;</td>
			<td class="column10">&nbsp;</td>
			<td class="column11">&nbsp;</td>
		  </tr>
		  <tr class="row25">
			<td class="column0 style29 null"></td>
			<td class="column1 style15 null"></td>
			<td class="column2 style35 s">인수인연락처:</td>
			<td class="column3 style15 null"></td>
			<td class="column4 style15 null"></td>
			<td class="column5 style15 null"></td>
			<td class="column6 style15 null"></td>
			<td class="column7 style15 null"></td>
			<td class="column8 style31 null"></td>
			<td class="column9">&nbsp;</td>
			<td class="column10">&nbsp;</td>
			<td class="column11">&nbsp;</td>
		  </tr>
		  <tr class="row26">
			<td class="column0 style29 null"></td>
			<td class="column1 style15 null"></td>
			<td class="column2 style15 null"></td>
			<td class="column3 style15 null"></td>
			<td class="column4 style36 null"></td>
			<td class="column5 style37 null"></td>
			<td class="column6 style37 null"></td>
			<td class="column7 style38 null"></td>
			<td class="column8 style31 null"></td>
			<td class="column9">&nbsp;</td>
			<td class="column10">&nbsp;</td>
			<td class="column11">&nbsp;</td>
		  </tr>
		  <tr class="row27">
			<td class="column0 style29 null"></td>
			<td class="column1 style15 null"></td>
			<td class="column2 style15 null"></td>
			<td class="column3 style15 null"></td>
			<td class="column4 style15 null"></td>
			<td class="column5 style37 null"></td>
			<td class="column6 style15 null"></td>
			<td class="column7 style15 null"></td>
			<td class="column8 style31 null"></td>
			<td class="column9">&nbsp;</td>
			<td class="column10">&nbsp;</td>
			<td class="column11">&nbsp;</td>
		  </tr>
		  <tr class="row28">
			<td class="column0 style29 null"></td>
			<td class="column1 style39 s">상기  본인은  ㈜에스비엠의  Banking  Machine</td>
			<td class="column2 style40 null"></td>
			<td class="column3 style15 null"></td>
			<td class="column4 style41 null"></td>
			<td class="column5 style41 null"></td>
			<td class="column6 style41 null"></td>
			<td class="column7 style41 null"></td>
			<td class="column8 style31 null"></td>
			<td class="column9">&nbsp;</td>
			<td class="column10">&nbsp;</td>
			<td class="column11">&nbsp;</td>
		  </tr>
		  <tr class="row29">
			<td class="column0 style29 null"></td>
			<td class="column1 style55 f style55" colspan="7">40</td>
			<td class="column8 style31 null"></td>
			<td class="column9">&nbsp;</td>
			<td class="column10">&nbsp;</td>
			<td class="column11">&nbsp;</td>
		  </tr>
		  <tr class="row30">
			<td class="column0 style29 null"></td>
			<td class="column1 style42 null"></td>
			<td class="column2 style43 f">Ladkani</td>
			<td class="column3 style5 null"></td>
			<td class="column4 style5 null"></td>
			<td class="column5 style56 f style56" colspan="3">2014&amp;quot;년&amp;quot;  04&amp;quot;월&amp;quot;  07&amp;quot;일&amp;quot;</td>
			<td class="column8 style31 null"></td>
			<td class="column9">&nbsp;</td>
			<td class="column10">&nbsp;</td>
			<td class="column11">&nbsp;</td>
		  </tr>
		  <tr class="row31">
			<td class="column0 style29 null"></td>
			<td class="column1 style44 null"></td>
			<td class="column2 style45 f">SB-9RL</td>
			<td class="column3 style46 f">40</td>
			<td class="column4 style5 null"></td>
			<td class="column5 style5 null"></td>
			<td class="column6 style5 null"></td>
			<td class="column7 style5 null"></td>
			<td class="column8 style31 null"></td>
			<td class="column9">&nbsp;</td>
			<td class="column10">&nbsp;</td>
			<td class="column11">&nbsp;</td>
		  </tr>
		  <tr class="row32">
			<td class="column0 style29 null"></td>
			<td class="column1 style44 null"></td>
			<td class="column2 style47 null"></td>
			<td class="column3 style48 null"></td>
			<td class="column4 style5 null"></td>
			<td class="column5 style5 null"></td>
			<td class="column6 style5 null"></td>
			<td class="column7 style5 null"></td>
			<td class="column8 style31 null"></td>
			<td class="column9">&nbsp;</td>
			<td class="column10">&nbsp;</td>
			<td class="column11">&nbsp;</td>
		  </tr>
		  <tr class="row33">
			<td class="column0 style49 null"></td>
			<td class="column1 style50 null"></td>
			<td class="column2 style51 null"></td>
			<td class="column3 style52 null"></td>
			<td class="column4 style50 null"></td>
			<td class="column5 style50 null"></td>
			<td class="column6 style50 null"></td>
			<td class="column7 style50 null"></td>
			<td class="column8 style53 null"></td>
			<td class="column9">&nbsp;</td>
			<td class="column10">&nbsp;</td>
			<td class="column11">&nbsp;</td>
		  </tr>
		  <tr class="row34">
			<td class="column0">&nbsp;</td>
			<td class="column1">&nbsp;</td>
			<td class="column2">&nbsp;</td>
			<td class="column3">&nbsp;</td>
			<td class="column4">&nbsp;</td>
			<td class="column5">&nbsp;</td>
			<td class="column6 style0 null">
<div style="position: relative;"><img style="position: absolute; z-index: 1; left: 86px; top: 0px; width: 147px; height: 0px;" src="zip://D:\dev\php\web\sbm\sbm.dealer\application\views\test\docs_02.xlsx#xl/media/image2.jpeg" border="0" /></div>
<div style="position: relative;"><img style="position: absolute; z-index: 1; left: 86px; top: 0px; width: 147px; height: 0px;" src="zip://D:\dev\php\web\sbm\sbm.dealer\application\views\test\docs_02.xlsx#xl/media/image2.jpeg" border="0" /></div>
<div style="position: relative;"><img style="position: absolute; z-index: 1; left: 86px; top: 0px; width: 147px; height: 0px;" src="zip://D:\dev\php\web\sbm\sbm.dealer\application\views\test\docs_02.xlsx#xl/media/image2.jpeg" border="0" /></div>
<div style="position: relative;"><img style="position: absolute; z-index: 1; left: 86px; top: 0px; width: 147px; height: 0px;" src="zip://D:\dev\php\web\sbm\sbm.dealer\application\views\test\docs_02.xlsx#xl/media/image2.jpeg" border="0" /></div>
<div style="position: relative;"><img style="position: absolute; z-index: 1; left: 86px; top: 0px; width: 147px; height: 0px;" src="zip://D:\dev\php\web\sbm\sbm.dealer\application\views\test\docs_02.xlsx#xl/media/image2.jpeg" border="0" /></div>
<div style="position: relative;"><img style="position: absolute; z-index: 1; left: 86px; top: 0px; width: 147px; height: 0px;" src="zip://D:\dev\php\web\sbm\sbm.dealer\application\views\test\docs_02.xlsx#xl/media/image2.jpeg" border="0" /></div>
<div style="position: relative;"><img style="position: absolute; z-index: 1; left: 86px; top: 0px; width: 147px; height: 0px;" src="zip://D:\dev\php\web\sbm\sbm.dealer\application\views\test\docs_02.xlsx#xl/media/image2.jpeg" border="0" /></div>
<div style="position: relative;"><img style="position: absolute; z-index: 1; left: 86px; top: 0px; width: 147px; height: 0px;" src="zip://D:\dev\php\web\sbm\sbm.dealer\application\views\test\docs_02.xlsx#xl/media/image2.jpeg" border="0" /></div>
<div style="position: relative;"><img style="position: absolute; z-index: 1; left: 86px; top: 0px; width: 147px; height: 0px;" src="zip://D:\dev\php\web\sbm\sbm.dealer\application\views\test\docs_02.xlsx#xl/media/image2.jpeg" border="0" /></div>
<div style="position: relative;"><img style="position: absolute; z-index: 1; left: 86px; top: 0px; width: 147px; height: 0px;" src="zip://D:\dev\php\web\sbm\sbm.dealer\application\views\test\docs_02.xlsx#xl/media/image2.jpeg" border="0" /></div></td>
			<td class="column7">&nbsp;</td>
			<td class="column8">&nbsp;</td>
			<td class="column9">&nbsp;</td>
			<td class="column10">&nbsp;</td>
			<td class="column11">&nbsp;</td>
		  </tr>
		</tbody>
	</table>
  </body>
</html>
