<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">
<!-- Generated by PHPExcel - http://www.phpexcel.net -->
<html>
  <head>
	  <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
	  <meta name="author" content="com" />
	  <meta name="company" content="Microsoft Corporation" />
	<style type="text/css">
	  html { font-family:Calibri, Arial, Helvetica, sans-serif; font-size:11pt; background-color:white }
	  table { border-collapse:collapse; page-break-after:always }
	  .gridlines td { border:1px dotted black }
	  .b { text-align:center }
	  .e { text-align:center }
	  .f { text-align:right }
	  .inlineStr { text-align:left }
	  .n { text-align:right }
	  .s { text-align:left }
	  td.style0 { vertical-align:middle; border-bottom:none #000000; border-top:none #000000; border-left:none #000000; border-right:none #000000; color:#000000; font-family:'돋움'; font-size:11pt; background-color:white }
	  td.style1 { vertical-align:middle; text-align:justify; border-bottom:none #000000; border-top:none #000000; border-left:none #000000; border-right:none #000000; color:#000000; font-family:'Arial'; font-size:10pt; background-color:white }
	  td.style2 { vertical-align:middle; border-bottom:none #000000; border-top:none #000000; border-left:none #000000; border-right:none #000000; color:#000000; font-family:'돋움'; font-size:11pt; background-color:white }
	  td.style3 { vertical-align:bottom; text-align:center; border-bottom:4px solid #000000; border-top:none #000000; border-left:none #000000; border-right:none #000000; color:#000000; font-family:'Arial'; font-size:18pt; background-color:white }
	  td.style4 { vertical-align:bottom; text-align:center; border-bottom:none #000000; border-top:none #000000; border-left:none #000000; border-right:none #000000; color:#000000; font-family:'돋움'; font-size:11pt; background-color:white }
	  td.style5 { vertical-align:middle; text-align:justify; border-bottom:none #000000; border-top:none #000000; border-left:none #000000; border-right:none #000000; color:#FF0000; font-family:'Arial'; font-size:10pt; background-color:white }
	  td.style6 { vertical-align:middle; border-bottom:none #000000; border-top:none #000000; border-left:none #000000; border-right:none #000000; color:#FF0000; font-family:'돋움'; font-size:11pt; background-color:white }
	  td.style7 { vertical-align:middle; text-align:left; padding-left:0px; border-bottom:none #000000; border-top:none #000000; border-left:none #000000; border-right:none #000000; font-weight:bold; color:#000000; font-family:'Arial'; font-size:11pt; background-color:white }
	  td.style8 { vertical-align:middle; text-align:justify; border-bottom:none #000000; border-top:none #000000; border-left:none #000000; border-right:none #000000; font-weight:bold; color:#000000; font-family:'Arial'; font-size:11pt; background-color:white }
	  td.style9 { vertical-align:middle; border-bottom:none #000000; border-top:none #000000; border-left:none #000000; border-right:none #000000; font-weight:bold; color:#000000; font-family:'Arial'; font-size:11pt; background-color:white }
	  td.style10 { vertical-align:top; border-bottom:none #000000; border-top:none #000000; border-left:none #000000; border-right:none #000000; font-style:italic; color:#000000; font-family:'Arial'; font-size:8pt; background-color:white }
	  td.style11 { vertical-align:middle; text-align:justify; border-bottom:none #000000; border-top:none #000000; border-left:none #000000; border-right:none #000000; color:#000000; font-family:'Arial'; font-size:10pt; background-color:white }
	  td.style12 { vertical-align:middle; text-align:center; border-bottom:1px solid #000000 !important; border-top:1px solid #000000 !important; border-left:1px solid #000000 !important; border-right:1px solid #000000 !important; font-weight:bold; color:#000000; font-family:'Arial'; font-size:10pt; background-color:white }
	  td.style13 { vertical-align:middle; text-align:center; border-bottom:1px solid #000000 !important; border-top:1px solid #000000 !important; border-left:none #000000; border-right:1px solid #000000 !important; font-weight:bold; color:#000000; font-family:'Arial'; font-size:10pt; background-color:white }
	  td.style14 { vertical-align:middle; text-align:center; border-bottom:none #000000; border-top:none #000000; border-left:1px solid #000000 !important; border-right:1px solid #000000 !important; font-weight:bold; color:#000000; font-family:'Arial'; font-size:9pt; background-color:white }
	  td.style15 { vertical-align:middle; text-align:left; padding-left:0px; border-bottom:none #000000; border-top:none #000000; border-left:none #000000; border-right:none #000000; color:#000000; font-family:'Arial'; font-size:9pt; background-color:white }
	  td.style16 { vertical-align:middle; border-bottom:none #000000; border-top:none #000000; border-left:none #000000; border-right:none #000000; color:#000000; font-family:'Arial'; font-size:9pt; background-color:white }
	  td.style17 { vertical-align:middle; text-align:center; border-bottom:none #000000; border-top:none #000000; border-left:1px solid #000000 !important; border-right:1px solid #000000 !important; color:#000000; font-family:'Arial'; font-size:9pt; background-color:white }
	  td.style18 { vertical-align:middle; text-align:right; padding-right:0px; border-bottom:none #000000; border-top:none #000000; border-left:none #000000; border-right:1px solid #000000 !important; color:#000000; font-family:'Arial'; font-size:9pt; background-color:white }
	  td.style19 { vertical-align:middle; text-align:right; padding-right:0px; border-bottom:none #000000; border-top:none #000000; border-left:none #000000; border-right:1px solid #000000 !important; color:#000000; font-family:'Arial'; font-size:9pt; background-color:white }
	  td.style20 { vertical-align:middle; border-bottom:none #000000; border-top:none #000000; border-left:none #000000; border-right:none #000000; color:#000000; font-family:'돋움'; font-size:9pt; background-color:white }
	  td.style21 { vertical-align:middle; border-bottom:none #000000; border-top:none #000000; border-left:1px solid #000000 !important; border-right:1px solid #000000 !important; color:#000000; font-family:'Arial'; font-size:9pt; background-color:white }
	  td.style22 { vertical-align:middle; border-bottom:none #000000; border-top:none #000000; border-left:none #000000; border-right:1px solid #000000 !important; color:#000000; font-family:'Arial'; font-size:9pt; background-color:white }
	  td.style23 { vertical-align:middle; text-align:right; padding-right:0px; border-bottom:none #000000; border-top:none #000000; border-left:none #000000; border-right:1px solid #000000 !important; color:#000000; font-family:'Arial'; font-size:9pt; background-color:white }
	  td.style24 { vertical-align:middle; text-align:left; padding-left:0px; border-bottom:none #000000; border-top:none #000000; border-left:none #000000; border-right:none #000000; font-weight:bold; color:#000000; font-family:'Arial'; font-size:9pt; background-color:white }
	  td.style25 { vertical-align:middle; text-align:center; border-bottom:none #000000; border-top:none #000000; border-left:1px solid #000000 !important; border-right:1px solid #000000 !important; font-weight:bold; color:#000000; font-family:'Arial'; font-size:9pt; background-color:white }
	  td.style26 { vertical-align:middle; text-align:left; padding-left:0px; border-bottom:none #000000; border-top:none #000000; border-left:none #000000; border-right:none #000000; font-weight:bold; color:#000000; font-family:'Arial'; font-size:9pt; background-color:white }
	  td.style27 { vertical-align:middle; border-bottom:none #000000; border-top:none #000000; border-left:none #000000; border-right:none #000000; color:#000000; font-family:'Arial'; font-size:9pt; background-color:white }
	  td.style28 { vertical-align:middle; text-align:center; border-bottom:none #000000; border-top:none #000000; border-left:1px solid #000000 !important; border-right:1px solid #000000 !important; color:#000000; font-family:'Arial'; font-size:9pt; background-color:white }
	  td.style29 { vertical-align:middle; border-bottom:none #000000; border-top:none #000000; border-left:none #000000; border-right:none #000000; color:#FF0000; font-family:'돋움'; font-size:9pt; background-color:white }
	  td.style30 { vertical-align:middle; text-align:left; padding-left:0px; border-bottom:none #000000; border-top:none #000000; border-left:none #000000; border-right:none #000000; color:#000000; font-family:'Arial'; font-size:9pt; background-color:white }
	  td.style31 { vertical-align:middle; border-bottom:none #000000; border-top:none #000000; border-left:1px solid #000000 !important; border-right:none #000000; color:#000000; font-family:'Arial'; font-size:9pt; background-color:white }
	  td.style32 { vertical-align:middle; border-bottom:none #000000; border-top:none #000000; border-left:none #000000; border-right:none #000000; color:#000000; font-family:'Arial'; font-size:9pt; background-color:white }
	  td.style33 { vertical-align:middle; text-align:center; border-bottom:none #000000; border-top:none #000000; border-left:1px solid #000000 !important; border-right:1px solid #000000 !important; color:#000000; font-family:'Arial'; font-size:10pt; background-color:white }
	  td.style34 { vertical-align:middle; text-align:right; padding-right:0px; border-bottom:none #000000; border-top:none #000000; border-left:1px solid #000000 !important; border-right:1px solid #000000 !important; color:#000000; font-family:'Arial'; font-size:9pt; background-color:white }
	  td.style35 { vertical-align:middle; border-bottom:1px solid #000000 !important; border-top:1px solid #000000 !important; border-left:1px solid #000000 !important; border-right:none #000000; font-weight:bold; color:#000000; font-family:'Arial'; font-size:10pt; background-color:white }
	  td.style36 { vertical-align:middle; border-bottom:1px solid #000000 !important; border-top:1px solid #000000 !important; border-left:none #000000; border-right:none #000000; font-weight:bold; color:#000000; font-family:'Arial'; font-size:10pt; background-color:white }
	  td.style37 { vertical-align:middle; text-align:right; padding-right:0px; border-bottom:1px solid #000000 !important; border-top:1px solid #000000 !important; border-left:none #000000; border-right:1px solid #000000 !important; font-weight:bold; color:#000000; font-family:'Arial'; font-size:10pt; background-color:white }
	  td.style38 { vertical-align:middle; border-bottom:none #000000; border-top:none #000000; border-left:none #000000; border-right:none #000000; color:#000000; font-family:'돋움'; font-size:11pt; background-color:white }
	  td.style39 { vertical-align:middle; text-align:left; padding-left:0px; border-bottom:none #000000; border-top:none #000000; border-left:none #000000; border-right:none #000000; color:#000000; font-family:'Arial'; font-size:10pt; background-color:white }
	  td.style40 { vertical-align:middle; text-align:right; padding-right:0px; border-bottom:none #000000; border-top:none #000000; border-left:none #000000; border-right:none #000000; color:#000000; font-family:'Arial'; font-size:10pt; background-color:white }
	  td.style41 { vertical-align:middle; border-bottom:none #000000; border-top:none #000000; border-left:none #000000; border-right:none #000000; color:#000000; font-family:'Arial'; font-size:10pt; background-color:white }
	  td.style42 { vertical-align:middle; text-align:left; padding-left:0px; border-bottom:none #000000; border-top:none #000000; border-left:none #000000; border-right:none #000000; color:#000000; font-family:'Arial'; font-size:10pt; background-color:white }
	  td.style43 { vertical-align:middle; border-bottom:none #000000; border-top:none #000000; border-left:none #000000; border-right:none #000000; color:#000000; font-family:'Arial'; font-size:10pt; background-color:white }
	  td.style44 { vertical-align:middle; text-align:left; padding-left:0px; border-bottom:none #000000; border-top:none #000000; border-left:none #000000; border-right:none #000000; color:#000000; font-family:'Arial'; font-size:10pt; background-color:white }
	  td.style45 { vertical-align:middle; text-align:justify; border-bottom:none #000000; border-top:none #000000; border-left:none #000000; border-right:none #000000; font-weight:bold; color:#000000; font-family:'Arial'; font-size:10pt; background-color:white }
	  td.style46 { vertical-align:middle; border-bottom:none #000000; border-top:none #000000; border-left:none #000000; border-right:none #000000; color:#000000; font-family:'Arial'; font-size:10pt; background-color:white }
	  td.style47 { vertical-align:middle; text-align:left; padding-left:9px; border-bottom:none #000000; border-top:1px solid #000000; border-left:none #000000; border-right:none #000000; font-weight:bold; color:#000000; font-family:'Arial'; font-size:12pt; background-color:white }
	  td.style48 { vertical-align:middle; border-bottom:none #000000; border-top:none #000000; border-left:none #000000; border-right:none #000000; font-weight:bold; color:#000000; font-family:'Arial'; font-size:12pt; background-color:white }
	  td.style49 { vertical-align:middle; border-bottom:none #000000; border-top:none #000000; border-left:none #000000; border-right:none #000000; color:#000000; font-family:'Arial'; font-size:12pt; background-color:white }
	  td.style50 { vertical-align:middle; text-align:left; padding-left:9px; border-bottom:none #000000; border-top:none #000000; border-left:none #000000; border-right:none #000000; color:#000000; font-family:'Arial'; font-size:9pt; background-color:white }
	  td.style51 { vertical-align:middle; border-bottom:none #000000; border-top:none #000000; border-left:none #000000; border-right:none #000000; color:#000000; font-family:'Arial'; font-size:9pt; background-color:white }
	  td.style52 { vertical-align:middle; text-align:center; border-bottom:none #000000; border-top:2px solid #000000; border-left:none #000000; border-right:none #000000; font-weight:bold; color:#000000; font-family:'Arial'; font-size:11pt; background-color:white }
	  td.style53 { vertical-align:middle; text-align:center; border-bottom:none #000000; border-top:none #000000; border-left:none #000000; border-right:none #000000; color:#000000; font-family:'돋움'; font-size:11pt; background-color:white }
	  td.style54 { vertical-align:middle; text-align:center; border-bottom:none #000000; border-top:none #000000; border-left:none #000000; border-right:none #000000; color:#000000; font-family:'Arial'; font-size:9pt; background-color:white }
	  td.style55 { vertical-align:middle; border-bottom:none #000000; border-top:none #000000; border-left:none #000000; border-right:none #000000; color:#000000; font-family:'Arial'; font-size:10pt; background-color:white }
	  td.style56 { vertical-align:middle; text-align:center; border-bottom:none #000000; border-top:none #000000; border-left:none #000000; border-right:none #000000; color:#000000; font-family:'돋움'; font-size:10pt; background-color:white }
	  td.style57 { vertical-align:middle; text-align:right; padding-right:0px; border-bottom:none #000000; border-top:none #000000; border-left:none #000000; border-right:none #000000; color:#000000; font-family:'돋움'; font-size:10pt; background-color:white }
	  td.style58 { vertical-align:middle; border-bottom:none #000000; border-top:none #000000; border-left:none #000000; border-right:none #000000; color:#000000; font-family:'돋움'; font-size:10pt; background-color:white }
	  td.style59 { vertical-align:middle; text-align:justify; border-bottom:none #000000; border-top:none #000000; border-left:none #000000; border-right:none #000000; font-weight:bold; color:#000000; font-family:'Arial'; font-size:12pt; background-color:white }
	  td.style60 { vertical-align:middle; text-align:left; padding-left:0px; border-bottom:none #000000; border-top:none #000000; border-left:none #000000; border-right:none #000000; color:#FF0000; font-family:'Arial'; font-size:10pt; background-color:white }
	  td.style61 { vertical-align:middle; text-align:left; padding-left:0px; border-bottom:none #000000; border-top:none #000000; border-left:none #000000; border-right:none #000000; font-weight:bold; color:#000000; font-family:'Arial'; font-size:10pt; background-color:white }
	  td.style62 { vertical-align:middle; text-align:left; padding-left:0px; border-bottom:none #000000; border-top:none #000000; border-left:none #000000; border-right:none #000000; color:#000000; font-family:'Arial'; font-size:10pt; background-color:white }
	  td.style63 { vertical-align:middle; text-align:right; padding-right:0px; border-bottom:none #000000; border-top:none #000000; border-left:none #000000; border-right:none #000000; color:#000000; font-family:'Arial'; font-size:10pt; background-color:white }
	  td.style64 { vertical-align:top; text-align:right; padding-right:0px; border-bottom:none #000000; border-top:none #000000; border-left:none #000000; border-right:none #000000; font-style:italic; color:#000000; font-family:'Arial'; font-size:8pt; background-color:white }
	  td.style65 { vertical-align:middle; text-align:left; padding-left:0px; border-bottom:1px solid #000000 !important; border-top:none #000000; border-left:none #000000; border-right:none #000000; color:#000000; font-family:'Arial'; font-size:10pt; background-color:white }
	  td.style66 { vertical-align:middle; text-align:center; border-bottom:1px solid #000000 !important; border-top:1px solid #000000 !important; border-left:none #000000; border-right:none #000000; font-weight:bold; color:#000000; font-family:'Arial'; font-size:10pt; background-color:white }
	  td.style67 { vertical-align:middle; text-align:center; border-bottom:1px solid #000000 !important; border-top:1px solid #000000 !important; border-left:1px solid #000000 !important; border-right:none #000000; font-weight:bold; color:#000000; font-family:'Arial'; font-size:10pt; background-color:white }
	  td.style68 { vertical-align:middle; text-align:center; border-bottom:1px solid #000000 !important; border-top:1px solid #000000 !important; border-left:none #000000; border-right:none #000000; font-weight:bold; color:#000000; font-family:'Arial'; font-size:10pt; background-color:white }
	  td.style69 { vertical-align:middle; text-align:center; border-bottom:1px solid #000000 !important; border-top:1px solid #000000 !important; border-left:none #000000; border-right:1px solid #000000 !important; font-weight:bold; color:#000000; font-family:'Arial'; font-size:10pt; background-color:white }
	  table.sheet0 col.col0 { width:42.02222174pt }
	  table.sheet0 col.col1 { width:16.26666648pt }
	  table.sheet0 col.col2 { width:12.87777763pt }
	  table.sheet0 col.col3 { width:104.37777658pt }
	  table.sheet0 col.col4 { width:39.31111066pt }
	  table.sheet0 col.col5 { width:58.28888822pt }
	  table.sheet0 col.col6 { width:58.28888822pt }
	  table.sheet0 col.col7 { width:42.02222174pt }
	  table.sheet0 tr { height:15pt }
	  table.sheet0 tr.row4 { height:34.5pt }
	  table.sheet0 tr.row6 { height:15pt }
	  table.sheet0 tr.row7 { height:15pt }
	  table.sheet0 tr.row8 { height:15pt }
	  table.sheet0 tr.row9 { height:5.25pt }
	  table.sheet0 tr.row10 { height:13.5pt }
	  table.sheet0 tr.row12 { height:12pt }
	  table.sheet0 tr.row13 { height:12pt }
	  table.sheet0 tr.row14 { height:12pt }
	  table.sheet0 tr.row15 { height:12pt }
	  table.sheet0 tr.row16 { height:12pt }
	  table.sheet0 tr.row17 { height:12pt }
	  table.sheet0 tr.row18 { height:12pt }
	  table.sheet0 tr.row19 { height:12pt }
	  table.sheet0 tr.row20 { height:12pt }
	  table.sheet0 tr.row21 { height:12pt }
	  table.sheet0 tr.row22 { height:12pt }
	  table.sheet0 tr.row23 { height:12pt }
	  table.sheet0 tr.row24 { height:12pt }
	  table.sheet0 tr.row25 { height:12.75pt }
	  table.sheet0 tr.row26 { height:13.5pt }
	  table.sheet0 tr.row27 { height:3.75pt }
	  table.sheet0 tr.row28 { height:12.75pt }
	  table.sheet0 tr.row29 { height:12.75pt }
	  table.sheet0 tr.row30 { height:12.75pt }
	  table.sheet0 tr.row31 { height:12.75pt }
	  table.sheet0 tr.row32 { height:12.75pt }
	  table.sheet0 tr.row33 { height:12.75pt }
	  table.sheet0 tr.row34 { height:12.75pt }
	  table.sheet0 tr.row35 { height:12.75pt }
	  table.sheet0 tr.row36 { height:12.75pt }
	  table.sheet0 tr.row37 { height:12.75pt }
	  table.sheet0 tr.row38 { height:12.75pt }
	  table.sheet0 tr.row39 { height:12.75pt }
	  table.sheet0 tr.row40 { height:12.75pt }
	  table.sheet0 tr.row41 { height:15.75pt }
	  table.sheet0 tr.row42 { height:12.75pt }
	  table.sheet0 tr.row43 { height:12.75pt }
	  table.sheet0 tr.row44 { height:12.75pt }
	  table.sheet0 tr.row45 { height:12.75pt }
	  table.sheet0 tr.row46 { height:12.75pt }
	  table.sheet0 tr.row47 { height:12.75pt }
	  table.sheet0 tr.row48 { height:5.25pt }
	  table.sheet0 tr.row49 { height:15.75pt }
	  table.sheet0 tr.row51 { height:15pt }
	  table.sheet0 tr.row54 { height:12.75pt }
	</style>
  </head>

  <body>
<style>
@page { left-margin: 0.98425196850394in; right-margin: 0.98425196850394in; top-margin: 0.19685039370079in; bottom-margin: 0.039370078740157in; }
body { left-margin: 0.98425196850394in; right-margin: 0.98425196850394in; top-margin: 0.19685039370079in; bottom-margin: 0.039370078740157in; }
</style>

	<table border="0" cellpadding="0" cellspacing="0" id="sheet0" style="width: 210mm;" align=center>
	<tr>
		<td colspan=10 align=right>
		<input type="button" value="save" onclick="javascript:save();"/>
		<input type="button" value="send" onclick="javascript:sendMail();" disabled/>
		</td>
	  </tr>
	</table>
	<p>

	<table border="0" cellpadding="0" cellspacing="0" id="sheet0" class="sheet0" style="width: 210mm;height: 290mm;" align=center>
		<col class="col0">
		<col class="col1">
		<col class="col2">
		<col class="col3">
		<col class="col4">
		<col class="col5">
		<col class="col6">
		<col class="col7">
		<tbody>
<!-- 		
		  <tr class="row0">
			<td class="column0 style1 null"></td>
			<td class="column1 style1 null"></td>
			<td class="column2 style1 null"></td>
			<td class="column3">&nbsp;</td>
			<td class="column4" colspan=3>
		  		<table border=0>
				  <tr>
					<td width=5% rowspan="2" class="style12">결<br/>재</td>
					<td colspan="2" width=70px class="style12">담당</td>
					<td colspan="2" width=70px class="style12">팀장</td>
					<td colspan="2" width=70px class="style12">이사</td>
					<td colspan="2" width=80px class="style12">대표이사</td>
				  </tr>
				  <tr height=70px>
				  	<td colspan="2" height=70px class="style12"></td>
					<td colspan="2" class="style12"></td>
					<td colspan="2" class="style12"></td>
					<td colspan="2" class="style12"></td>
				  </tr>
		  		</table>
			</td>
		  </tr>
 -->		  
		  <tr class="row4">
			<td class="column0 style3 s" colspan=7>PROFORMA INVOICE</td>
		  </tr>
		  <tr class="row5">
			<td class="column0 style1 s">&nbsp;</td>
			<td class="column1 style1 null"></td>
			<td class="column2 style1 null"></td>
			<td class="column3">&nbsp;</td>
			<td class="column4">&nbsp;</td>
			<td class="column5">&nbsp;</td>
			<td class="column6">&nbsp;</td>
		  </tr>
		  <tr class="row6">
			<td class="column0 style62 n style62" colspan="3">Date: 21 Mar., 2014</td>
			<td class="column3 style5 null"></td>
			<td class="column4">&nbsp;</td>
			<td class="column5 style63 n style63" colspan="2">Our Ref: PI-140321-7</td>
		  </tr>
		  <tr class="row7">
			<td class="column0 style7 s">Messrs.</td>
			<td class="column1 style7 s" colspan=4>: Ladkani Office Solutions</td>
			<td class="column5 style64 null style64" colspan="2"></td>
		  </tr>
		  <tr class="row8">
			<td class="column0 style8 s">Attn.</td>
			<td class="column1 style9 s" colspan=5>: Mr. Imad Ladkani</td>
			<td class="column6 style10 null"></td>
		  </tr>
		  <tr class="row9">
			<td class="column0 style11 null"></td>
			<td class="column1 style11 null"></td>
			<td class="column2 style11 null"></td>
			<td class="column3">&nbsp;</td>
			<td class="column4">&nbsp;</td>
			<td class="column5 style10 null"></td>
			<td class="column6 style10 null"></td>
		  </tr>
		  
		  <tr class="row10">
			<td class="column0 style65 s style65" colspan="7">We are pleased to confirm your order for the under-mentioned article(s) as per conditions and details described as follows:</td>
		  </tr>
		  <tr class="row11">
		  	<td class="column0 style12 s" style="border-left:1px solid #000000">Model</td>
			<td class="column1 style66 s style66" colspan="3">Description</td>
			<td class="column4 style12 s">Q’ty</td>
			<td class="column5 style13 s">Unit Price</td>
			<td class="column6 style13 s">Amount</td>
		  </tr>
		  <tr class="row12">
			<td class="column0 style14 s">SB-9</td>
			<td class="column1 style15 s" colspan="3">Currency Discrimination Counter</td>
			<td class="column4 style17 n">40</td>
			<td class="column5 style18 n">0</td>
			<td class="column6 style19 f">0</td>
		  </tr>
		  <tr class="row13">
			<td class="column0 style21 null"></td>
			<td class="column1 style15 s" colspan="3">Counterfeit Detection: MG, MR-Array, IR, UV </td>
			<td class="column4 style17 null"></td>
			<td class="column5 style22 null"></td>
			<td class="column6 style23 null"></td>
		  </tr>
		  <tr class="row14">
			<td class="column0 style21 null"></td>
			<td class="column1 style15 s" colspan="3">For LBP/USD/EUR only  /  P-OCR for USD/EUR</td>
			<td class="column4 style17 null"></td>
			<td class="column5 style22 null"></td>
			<td class="column6 style23 s">.</td>
		  </tr>
		  <tr class="row15">
			<td class="column0 style21 null"></td>
			<td class="column1 style15 null"></td>
			<td class="column2 style16 null"></td>
			<td class="column3 style16 null"></td>
			<td class="column4 style17 null"></td>
			<td class="column5 style22 null"></td>
			<td class="column6 style23 null"></td>
		  </tr>
		  <tr class="row17">
			<td class="column0 style25 null"></td>
			<td class="column1 style26 null"></td>
			<td class="column2 style27 null"></td>
			<td class="column3 style27 null"></td>
			<td class="column4 style28 null"></td>
			<td class="column5 style18 null"></td>
			<td class="column6 style18 null"></td>
		  </tr>
		  <tr class="row18">
			<td class="column0 style25 null"></td>
			<td class="column1 style26 s" colspan="3">Spare Parts</td>
			<td class="column4 style28 null"></td>
			<td class="column5 style18 null"></td>
			<td class="column6 style18 null"></td>
		  </tr>
		  <tr class="row19">
			<td class="column0 style25 null"></td>
			<td class="column1 style30 s" colspan="3">SB-1100  CIS</td>
			<td class="column4 style28 n">5</td>
			<td class="column5 style18 n">USD  130.00</td>
			<td class="column6 style19 f">USD  650.00</td>
		  </tr>
		  <tr class="row20">
			<td class="column0 style25 null"></td>
			<td class="column1 style30 s" colspan="3">SB-9  P_POWER_IO V1.5</td>
			<td class="column4 style28 n">5</td>
			<td class="column5 style18 n">USD  85.00</td>
			<td class="column6 style19 f">USD  425.00</td>
		  </tr>
		  <tr class="row21">
			<td class="column0 style25 null"></td>
			<td class="column1 style30 s" colspan="3">SB-9  MAIN V1.3</td>
			<td class="column4 style28 n">5</td>
			<td class="column5 style18 n">USD  220.00</td>
			<td class="column6 style19 f">USD  1,100.00</td>
		  </tr>
		  <tr class="row22">
			<td class="column0 style25 null"></td>
			<td class="column1 style30 null"></td>
			<td class="column2 style27 null"></td>
			<td class="column3 style27 null"></td>
			<td class="column4 style28 null"></td>
			<td class="column5 style18 null"></td>
			<td class="column6 style18 null"></td>
		  </tr>
		  <tr class="row26">
			<td class="column0 style67 s style69" colspan="4">Total Amount (FOB)</td>
			<td class="column4 style35 null"></td>
			<td class="column5 style36 null"></td>
			<td class="column6 style37 f">USD  2,175.00</td>
		  </tr>

		  <tr class="row16">
			<td class="column0 style14 s">
			<select name="printer">
				<option>Printer</option>
			</select>
			</td>
			<td class="column1 style24 s" colspan="3"><input type=text name="description" value="SP-58S" size=8 disabled></td>
			<td class="column4 style17 n"><input type=text name="qty" value="0" size=8></td>
			<td class="column5 style19 n"><input type=text name="qty" value="0" size=8 disabled></td>
			<td class="column6 style19 f"><input type=text name="qty" value="0" size=8 disabled></td>
		  </tr>
		  <tr class="row22">
			<td class="column0 style25 null"></td>
			<td class="column1 style30 null"></td>
			<td class="column2 style27 null"></td>
			<td class="column3 style27 null"></td>
			<td class="column4 style28 null"></td>
			<td class="column5 style18 null"></td>
			<td class="column6 style18 null"></td>
		  </tr>
		  <tr class="row16">
			<td class="column0 style14 s">
			<select name="printer">
				<option>Repair Parts</option>
			</select>
			</td>
			<td class="column1 style24 s" colspan="3"><input type=text name="description" value="SP-58S" size=8 disabled></td>
			<td class="column4 style17 n"><input type=text name="qty" value="0" size=8></td>
			<td class="column5 style19 n"></td>
			<td class="column6 style19 f"><input type=text name="qty" value="0" size=8></td>
		  </tr>
		  
		  <tr class="row25">
			<td class="column0 style14 null"></td>
			<td class="column1 style31 null"></td>
			<td class="column2 style32 null"></td>
			<td class="column3 style32 null"></td>
			<td class="column4 style33 null"></td>
			<td class="column5 style19 null"></td>
			<td class="column6 style34 null"></td>
		  </tr>
		  <tr class="row27">
			<td class="column0 style11 null"></td>
			<td class="column1 style11 null"></td>
			<td class="column2 style11 null"></td>
			<td class="column3">&nbsp;</td>
			<td class="column4">&nbsp;</td>
			<td class="column5">&nbsp;</td>
			<td class="column6 style38 null"></td>
		  </tr>
		  <tr class="row28">
			<td class="column0 style39 s" colspan=2>Origin</td>
			<td class="column2 style40 s">:</td>
			<td class="column3 style39 s" colspan=4>Republic of Korea</td>
		  </tr>
		  <tr class="row29">
			<td class="column0 style39 s" colspan=2>Packing</td>
			<td class="column2 style40 s">:</td>
			<td class="column3 style39 s" colspan=4>Export standard carton packing</td>
		  </tr>
		  <tr class="row30">
			<td class="column0 style39 s" colspan=2>Shipment</td>
			<td class="column2 style40 s">:</td>
			<td class="column3 style61 s style61" colspan="3">To be announced</td>
			<td class="column6">&nbsp;</td>
		  </tr>
		  <tr class="row31">
			<td class="column0 style39 s" colspan=2>Shipping port</td>
			<td class="column2 style40 s">:</td>
			<td class="column3 style39 s" colspan=4>
			<select name="shipping_port">
				<option>Incheon, Korea</option>
			</select>
			 (Shipped by AIR)
			</td>
		  </tr>
		  <tr class="row32">
			<td class="column0 style39 s" colspan=2>Inspection</td>
			<td class="column2 style40 s">:</td>
			<td class="column3 style39 s" colspan=4>Final inspection shall be made at the SBM’s factory</td>
		  </tr>
		  <tr class="row33">
			<td class="column0 style39 s" colspan=2>Destination</td>
			<td class="column2 style40 s">:</td>
			<td class="column3 style39 s" colspan=4><input type=text name="final_dest" value="Beirut" size=8>, Lebanon</td>
		  </tr>
		  <tr class="row34">
			<td class="column0 style39 s" colspan=2>Payment</td>
			<td class="column2 style40 s">:</td>
			<td class="column3 style39 s" colspan=4>
			<select name="payment">
				<option>T/T in advance</option>
			</select>
			 (All expenses outside of Korea shall be charged by remitter)
			</td>
		  </tr>
		  <tr class="row35">
			<td class="column0 style39 s" colspan=2>Validity</td>
			<td class="column2 style40 s">:</td>
			<td class="column3 style42 f">Until <INPUT type=text id="validity" name="validity" value="Apr. 18, 2014" size=10></td>
			<td class="column4 style43 null"></td>
			<td class="column5 style43 null"></td>
			<td class="column6">&nbsp;</td>
		  </tr>
		  <tr class="row36">
			<td class="column0 style44 s" colspan=2>Bank Information</td>
			<td class="column2 style40 s">:</td>
			<td class="column3 style60 s" colspan=4>
			<select name="bank_inf">
				<option value="CITI BANK INC.-Commercial Bank Center-Gyeonggi Nambu
				2F, CITI Osan Bldg., 84 Seongho-daero
				Osan-si, Gyeonggi-do, 447-804, KOREA
				SWIFT Code: CITIKRSX
				Account No.: 558-00113-436-01">CITI BANK INC
				</option>
				<option value="HANABANK, GASAN-DONG BRANCH 
     550-1, GASAN-DONG, GEUMCHEON-GU, SEOUL, KOREA 
     SWIFT CODE: HNBNKRSE 
     Account No.: 332-910001-81938 
				">HANABANK
				</option>
				</select>
			</td>
		  </tr>
		  <tr class="row40">
			<td class="column0 style1 s">Reference:</td>
			<td class="column1 style45 null"></td>
			<td class="column2 style40 s">:</td>
			<td class="column3 style41 s" colspan=4>If you delay the Ex-works date already agreed with us </td>
		  </tr>
		  <tr class="row41">
			<td class="column0 style1 null"></td>
			<td class="column1 style59 null"></td>
			<td class="column2 style59 null"></td>
			<td class="column3 style41 s" colspan=4>we duly inform that the new date is subject to our production schedule.</td>
		  </tr>
		  <tr class="row42">
			<td class="column0 style45 null"></td>
			<td class="column1 style45 null"></td>
			<td class="column2 style45 null"></td>
			<td class="column3">&nbsp;</td>
			<td class="column4">&nbsp;</td>
			<td class="column5">&nbsp;</td>
			<td class="column6">&nbsp;</td>
		  </tr>
		  <tr class="row43">
			<td class="column0 style45 null"></td>
			<td class="column1 style45 null"></td>
			<td class="column2 style45 null"></td>
			<td class="column3">&nbsp;</td>
			<td class="column4">&nbsp;</td>
			<td class="column5">&nbsp;</td>
			<td class="column6">&nbsp;</td>
		  </tr>
		  <tr class="row44">
			<td class="column0 style45 null"></td>
			<td class="column1 style45 null"></td>
			<td class="column2 style45 null"></td>
			<td class="column3">&nbsp;</td>
			<td class="column4">&nbsp;</td>
			<td class="column5">&nbsp;</td>
			<td class="column6">&nbsp;</td>
		  </tr>
		  <tr class="row45">
			<td class="column0 style45 null"></td>
			<td class="column1 style45 null"></td>
			<td class="column2 style45 null"></td>
			<td class="column3">&nbsp;</td>
			<td class="column4">&nbsp;</td>
			<td class="column5">&nbsp;</td>
			<td class="column6">&nbsp;</td>
		  </tr>
		  <tr class="row46">
			<td class="column0 style45 null"></td>
			<td class="column1 style45 null"></td>
			<td class="column2 style45 null"></td>
			<td class="column3">&nbsp;</td>
			<td class="column4">&nbsp;</td>
			<td class="column5">&nbsp;</td>
			<td class="column6">&nbsp;</td>
		  </tr>
		  <tr class="row47">
			<td class="column0 style45 null"></td>
			<td class="column1 style45 null"></td>
			<td class="column2 style45 null"></td>
			<td class="column3">&nbsp;</td>
			<td class="column4">&nbsp;</td>
			<td class="column5">&nbsp;</td>
			<td class="column6">&nbsp;</td>
		  </tr>
		  <tr class="row48">
			<td class="column0 style46 null"></td>
			<td class="column1 style46 null"></td>
			<td class="column2 style46 null"></td>
			<td class="column3">&nbsp;</td>
			<td class="column4">&nbsp;</td>
			<td class="column5">&nbsp;</td>
			<td class="column6">&nbsp;</td>
		  </tr>
		  <tr class="row49">
			<td class="column0 style47 s" colspan=5>Arthur Kim</td>
			<td class="column5 style2 null"></td>
			<td class="column6 style2 null"></td>
		  </tr>
		  <tr class="row50">
			<td class="column0 style50 s" colspan=7>Sales and Marketing Dept. / Senior Manager</td>
		  </tr>
		  <tr class="row51">
			<td class="column0 style52 s" colspan=7>SBM Co., Ltd.</td>
		  </tr>
		  <tr class="row52">
			<td class="column0 style54 s" colspan=7>6F, Hyunwoo Bld, 206, Anyang7-Dong, Manan-Gu, Anyang-City, Gyeonggi-Do, KOREA . 430-817</td>
		  </tr>
		  <tr class="row53">
			<td class="column0 style54 s" colspan=7>Tel: +82-31-429-0789    Fax: +82-31-429-3607</td>
		  </tr>
		  <tr class="row54">
			<td class="column0 style55 s" colspan=3>SBM-<span style="color:#000000; font-family:'돋움'; font-size:10pt">영업</span><span style="color:#000000; font-family:'Arial'; font-size:10pt">-P-701-02</span></td>
			<td class="column3 style57 s">㈜에스비엠</td>
			<td class="column4 style56 null"></td>
			<td class="column5 style56 null"></td>
			<td class="column6 style57 s">A4(210 X297mm)</td>
		  </tr>
		</tbody>
	</table>
  </body>
</html>
