<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">
<!-- Generated by PHPExcel - http://www.phpexcel.net -->
<html>
  <head>
	  <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
	  <meta name="author" content="KPBAEK" />
	  <meta name="company" content="Microsoft Corporation" />
	<style type="text/css">
	  html { font-family:Calibri, Arial, Helvetica, sans-serif; font-size:11pt; background-color:white }
	  table { border-collapse:collapse; page-break-after:always }
	  .gridlines td { border:1px dotted black }
	  .b { text-align:center }
	  .e { text-align:center }
	  .f { text-align:right }
	  .inlineStr { text-align:left }
	  .n { text-align:right }
	  .s { text-align:left }
	  td.style0 { vertical-align:middle; border-bottom:none #000000; border-top:none #000000; border-left:none #000000; border-right:none #000000; color:#000000; font-family:'맑은 고딕'; font-size:11pt; background-color:white }
	  td.style1 { vertical-align:middle; text-align:center; border-bottom:none #000000; border-top:none #000000; border-left:none #000000; border-right:none #000000; font-weight:bold; color:#000000; font-family:'Arial'; font-size:10pt; background-color:white }
	  td.style2 { vertical-align:middle; text-align:center; border-bottom:none #000000; border-top:none #000000; border-left:none #000000; border-right:1px solid #000000 !important; font-weight:bold; color:#000000; font-family:'Arial'; font-size:10pt; background-color:white }
	  td.style3 { vertical-align:middle; border-bottom:none #000000; border-top:none #000000; border-left:none #000000; border-right:none #000000; color:#000000; font-family:'Arial'; font-size:10pt; background-color:white }
	  td.style4 { vertical-align:middle; border-bottom:1px solid #000000 !important; border-top:1px solid #000000 !important; border-left:1px solid #000000 !important; border-right:none #000000; color:#000000; font-family:'Arial'; font-size:10pt; background-color:white }
	  td.style5 { vertical-align:middle; border-bottom:1px solid #000000 !important; border-top:1px solid #000000 !important; border-left:none #000000; border-right:none #000000; color:#000000; font-family:'Arial'; font-size:10pt; background-color:white }
	  td.style6 { vertical-align:middle; text-align:center; border-bottom:1px solid #000000 !important; border-top:1px solid #000000 !important; border-left:none #000000; border-right:none #000000; color:#000000; font-family:'Arial'; font-size:10pt; background-color:white }
	  td.style7 { vertical-align:middle; text-align:left; padding-left:0px; border-bottom:1px solid #000000 !important; border-top:1px solid #000000 !important; border-left:none #000000; border-right:none #000000; color:#000000; font-family:'Arial'; font-size:10pt; background-color:white }
	  td.style8 { vertical-align:middle; text-align:left; padding-left:0px; border-bottom:1px solid #000000 !important; border-top:1px solid #000000 !important; border-left:none #000000; border-right:1px solid #000000 !important; color:#000000; font-family:'Arial'; font-size:10pt; background-color:white }
	  td.style9 { vertical-align:middle; text-align:center; border-bottom:1px solid #000000 !important; border-top:1px solid #000000 !important; border-left:1px solid #000000 !important; border-right:1px solid #000000 !important; color:#000000; font-family:'Arial'; font-size:10pt; background-color:white }
	  td.style10 { vertical-align:middle; text-align:center; border-bottom:1px solid #000000 !important; border-top:1px solid #000000 !important; border-left:1px solid #000000 !important; border-right:1px solid #000000 !important; color:#000000; font-family:'Arial'; font-size:10pt; background-color:white }
	  td.style11 { vertical-align:middle; text-align:center; border-bottom:1px solid #000000 !important; border-top:1px solid #000000 !important; border-left:1px solid #000000 !important; border-right:none #000000; color:#000000; font-family:'Arial'; font-size:10pt; background-color:white }
	  td.style12 { vertical-align:middle; text-align:center; border-bottom:1px solid #000000 !important; border-top:1px solid #000000 !important; border-left:1px solid #000000 !important; border-right:1px solid #000000 !important; color:#000000; font-family:'Arial'; font-size:10pt; background-color:white }
	  td.style13 { vertical-align:middle; text-align:center; border-bottom:1px solid #000000 !important; border-top:1px solid #000000 !important; border-left:1px solid #000000 !important; border-right:1px solid #000000 !important; color:#000000; font-family:'Arial'; font-size:10pt; background-color:white }
	  td.style14 { vertical-align:middle; border-bottom:none #000000; border-top:none #000000; border-left:none #000000; border-right:none #000000; color:#000000; font-family:'Arial'; font-size:10pt; background-color:white }
	  td.style15 { vertical-align:middle; text-align:center; border-bottom:1px solid #000000 !important; border-top:1px solid #000000 !important; border-left:1px solid #000000 !important; border-right:1px solid #000000 !important; color:#000000; font-family:'Arial'; font-size:10pt; background-color:white }
	  td.style16 { vertical-align:middle; text-align:left; padding-left:0px; border-bottom:1px solid #000000 !important; border-top:1px solid #000000 !important; border-left:1px solid #000000 !important; border-right:1px solid #000000 !important; color:#000000; font-family:'Arial'; font-size:10pt; background-color:white }
	  td.style17 { vertical-align:middle; border-bottom:1px solid #000000 !important; border-top:1px solid #000000 !important; border-left:1px solid #000000 !important; border-right:1px solid #000000 !important; color:#000000; font-family:'Arial'; font-size:10pt; background-color:white }
	  td.style18 { vertical-align:bottom; border-bottom:1px solid #000000 !important; border-top:1px solid #000000 !important; border-left:1px solid #000000 !important; border-right:1px solid #000000 !important; color:#000000; font-family:'Arial'; font-size:10pt; background-color:#FBD4B4 }
	  td.style19 { vertical-align:middle; border-bottom:1px solid #000000 !important; border-top:1px solid #000000 !important; border-left:1px solid #000000 !important; border-right:none #000000; color:#000000; font-family:'Arial'; font-size:10pt; background-color:white }
	  td.style20 { vertical-align:bottom; border-bottom:1px solid #000000 !important; border-top:1px solid #000000 !important; border-left:1px solid #000000 !important; border-right:1px solid #000000 !important; color:#000000; font-family:'Arial'; font-size:10pt; background-color:white }
	  td.style21 { vertical-align:bottom; border-bottom:none #000000; border-top:none #000000; border-left:none #000000; border-right:none #000000; color:#000000; font-family:'Arial'; font-size:10pt; background-color:white }
	  td.style22 { vertical-align:bottom; border-bottom:1px solid #000000 !important; border-top:1px solid #000000 !important; border-left:1px solid #000000 !important; border-right:1px solid #000000 !important; color:#000000; font-family:'Arial'; font-size:10pt; background-color:white }
	  td.style23 { vertical-align:middle; text-align:left; padding-left:0px; border-bottom:1px solid #000000 !important; border-top:1px solid #000000 !important; border-left:1px solid #000000 !important; border-right:1px solid #000000 !important; color:#000000; font-family:'Arial'; font-size:10pt; background-color:white }
	  td.style24 { vertical-align:middle; text-align:center; border-bottom:1px solid #000000 !important; border-top:1px solid #000000 !important; border-left:1px solid #000000 !important; border-right:1px solid #000000 !important; color:#000000; font-family:'Arial'; font-size:10pt; background-color:white }
	  td.style25 { vertical-align:middle; text-align:left; padding-left:0px; border-bottom:1px solid #000000 !important; border-top:1px solid #000000 !important; border-left:1px solid #000000 !important; border-right:1px solid #000000 !important; color:#000000; font-family:'Arial'; font-size:10pt; background-color:white }
	  td.style26 { vertical-align:middle; text-align:center; border-bottom:1px solid #000000 !important; border-top:1px solid #000000 !important; border-left:1px solid #000000 !important; border-right:1px solid #000000 !important; color:#0000FF; font-family:'Arial'; font-size:10pt; background-color:#FBD4B4 }
	  td.style27 { vertical-align:bottom; border-bottom:none #000000; border-top:none #000000; border-left:none #000000; border-right:none #000000; color:#000000; font-family:'Arial'; font-size:10pt; background-color:white }
	  td.style28 { vertical-align:bottom; border-bottom:none #000000; border-top:none #000000; border-left:none #000000; border-right:none #000000; color:#000000; font-family:'Arial'; font-size:10pt; background-color:white }
	  td.style29 { vertical-align:bottom; border-bottom:1px solid #000000 !important; border-top:1px solid #000000 !important; border-left:1px solid #000000 !important; border-right:1px solid #000000 !important; color:#000000; font-family:'Arial'; font-size:10pt; background-color:white }
	  td.style30 { vertical-align:middle; border-bottom:1px solid #000000 !important; border-top:1px solid #000000 !important; border-left:1px solid #000000 !important; border-right:1px solid #000000 !important; color:#000000; font-family:'Arial'; font-size:10pt; background-color:white }
	  td.style31 { vertical-align:bottom; border-bottom:1px solid #000000 !important; border-top:1px solid #000000 !important; border-left:1px solid #000000 !important; border-right:1px solid #000000 !important; color:#000000; font-family:'Arial'; font-size:10pt; background-color:white }
	  td.style32 { vertical-align:bottom; border-bottom:none #000000; border-top:none #000000; border-left:none #000000; border-right:none #000000; color:#000000; font-family:'Arial'; font-size:10pt; background-color:white }
	  td.style33 { vertical-align:middle; text-align:left; padding-left:0px; border-bottom:1px solid #000000 !important; border-top:1px solid #000000 !important; border-left:1px solid #000000 !important; border-right:1px solid #000000 !important; color:#000000; font-family:'Arial'; font-size:10pt; background-color:white }
	  td.style34 { vertical-align:middle; text-align:left; padding-left:0px; border-bottom:1px solid #000000 !important; border-top:1px solid #000000 !important; border-left:1px solid #000000 !important; border-right:1px solid #000000 !important; color:#000000; font-family:'Arial'; font-size:10pt; background-color:white }
	  td.style35 { vertical-align:middle; text-align:left; padding-left:0px; border-bottom:1px solid #000000 !important; border-top:1px solid #000000 !important; border-left:1px solid #000000 !important; border-right:1px solid #000000 !important; color:#000000; font-family:'Arial'; font-size:10pt; background-color:white }
	  td.style36 { vertical-align:middle; text-align:left; padding-left:0px; border-bottom:1px solid #000000 !important; border-top:1px solid #000000 !important; border-left:1px solid #000000 !important; border-right:1px solid #000000 !important; color:#000000; font-family:'Arial'; font-size:10pt; background-color:white }
	  td.style37 { vertical-align:middle; text-align:center; border-bottom:1px solid #000000 !important; border-top:1px solid #000000 !important; border-left:1px solid #000000 !important; border-right:1px solid #000000 !important; color:#000000; font-family:'Arial'; font-size:10pt; background-color:white }
	  td.style38 { vertical-align:middle; text-align:left; padding-left:0px; border-bottom:1px solid #000000 !important; border-top:1px solid #000000 !important; border-left:1px solid #000000 !important; border-right:1px solid #000000 !important; color:#000000; font-family:'Arial'; font-size:10pt; background-color:white }
	  td.style39 { vertical-align:middle; text-align:left; padding-left:0px; border-bottom:1px solid #000000 !important; border-top:1px solid #000000 !important; border-left:1px solid #000000 !important; border-right:1px solid #000000 !important; color:#000000; font-family:'Arial'; font-size:10pt; background-color:white }
	  td.style40 { vertical-align:middle; text-align:left; padding-left:0px; border-bottom:1px solid #000000 !important; border-top:1px solid #000000 !important; border-left:1px solid #000000 !important; border-right:1px solid #000000 !important; color:#000000; font-family:'Arial'; font-size:10pt; background-color:white }
	  td.style41 { vertical-align:middle; text-align:center; border-bottom:1px solid #000000 !important; border-top:1px solid #000000 !important; border-left:1px solid #000000 !important; border-right:1px solid #000000 !important; color:#000000; font-family:'Arial'; font-size:10pt; background-color:#FFFFFF }
	  td.style42 { vertical-align:middle; border-bottom:1px solid #000000 !important; border-top:1px solid #000000 !important; border-left:1px solid #000000 !important; border-right:1px solid #000000 !important; color:#000000; font-family:'Arial'; font-size:10pt; background-color:white }
	  td.style43 { vertical-align:middle; text-align:left; padding-left:0px; border-bottom:1px solid #000000 !important; border-top:1px solid #000000 !important; border-left:none #000000; border-right:1px solid #000000 !important; color:#000000; font-family:'Arial'; font-size:10pt; background-color:white }
	  td.style44 { vertical-align:middle; text-align:center; border-bottom:1px solid #000000 !important; border-top:none #000000; border-left:1px solid #000000 !important; border-right:1px solid #000000 !important; color:#000000; font-family:'Arial'; font-size:10pt; background-color:white }
	  td.style45 { vertical-align:middle; text-align:center; border-bottom:1px solid #000000 !important; border-top:1px solid #000000 !important; border-left:1px solid #000000 !important; border-right:1px solid #000000 !important; color:#000000; font-family:'Arial'; font-size:10pt; background-color:white }
	  td.style46 { vertical-align:middle; text-align:left; padding-left:0px; border-bottom:1px solid #000000 !important; border-top:1px solid #000000 !important; border-left:1px solid #000000 !important; border-right:1px solid #000000 !important; color:#000000; font-family:'Arial'; font-size:10pt; background-color:white }
	  td.style47 { vertical-align:middle; text-align:center; border-bottom:1px solid #000000 !important; border-top:1px solid #000000 !important; border-left:1px solid #000000 !important; border-right:1px solid #000000 !important; color:#000000; font-family:'Arial'; font-size:10pt; background-color:white }
	  td.style48 { vertical-align:middle; border-bottom:1px solid #000000 !important; border-top:1px solid #000000 !important; border-left:1px solid #000000 !important; border-right:1px solid #000000 !important; color:#000000; font-family:'Arial'; font-size:10pt; background-color:white }
	  td.style49 { vertical-align:middle; text-align:center; border-bottom:none #000000; border-top:none #000000; border-left:none #000000; border-right:none #000000; color:#000000; font-family:'Arial'; font-size:10pt; background-color:white }
	  td.style50 { vertical-align:middle; text-align:center; border-bottom:none #000000; border-top:none #000000; border-left:none #000000; border-right:none #000000; color:#000000; font-family:'Arial'; font-size:10pt; background-color:white }
	  td.style51 { vertical-align:middle; border-bottom:none #000000; border-top:none #000000; border-left:none #000000; border-right:none #000000; color:#000000; font-family:'Arial'; font-size:10pt; background-color:white }
	  td.style52 { vertical-align:bottom; border-bottom:none #000000; border-top:none #000000; border-left:none #000000; border-right:none #000000; color:#000000; font-family:'Arial'; font-size:10pt; background-color:white }
	  td.style53 { vertical-align:middle; border-bottom:none #000000; border-top:none #000000; border-left:none #000000; border-right:none #000000; color:#000000; font-family:'Arial'; font-size:10pt; background-color:white }
	  td.style54 { vertical-align:middle; text-align:left; padding-left:0px; border-bottom:none #000000; border-top:none #000000; border-left:none #000000; border-right:none #000000; color:#000000; font-family:'Arial'; font-size:10pt; background-color:white }
	  td.style55 { vertical-align:middle; text-align:center; border-bottom:none #000000; border-top:none #000000; border-left:none #000000; border-right:none #000000; color:#000000; font-family:'Arial'; font-size:10pt; background-color:white }
	  td.style56 { vertical-align:middle; text-align:right; padding-right:0px; border-bottom:none #000000; border-top:none #000000; border-left:none #000000; border-right:none #000000; color:#000000; font-family:'Arial'; font-size:10pt; background-color:white }
	  td.style57 { vertical-align:middle; border-bottom:none #000000; border-top:none #000000; border-left:none #000000; border-right:none #000000; color:#000000; font-family:'Arial'; font-size:10pt; background-color:white }
	  td.style58 { vertical-align:middle; border-bottom:none #000000; border-top:none #000000; border-left:none #000000; border-right:none #000000; color:#000000; font-family:'Arial'; font-size:10pt; background-color:white }
	  td.style59 { vertical-align:middle; text-align:right; padding-right:0px; border-bottom:1px solid #000000 !important; border-top:1px solid #000000 !important; border-left:1px solid #000000 !important; border-right:1px solid #000000 !important; color:#000000; font-family:'Arial'; font-size:10pt; background-color:#FBD4B4 }
	  td.style60 { vertical-align:middle; border-bottom:1px solid #000000 !important; border-top:1px solid #000000 !important; border-left:1px solid #000000 !important; border-right:1px solid #000000 !important; color:#000000; font-family:'Arial'; font-size:10pt; background-color:white }
	  td.style61 { vertical-align:middle; border-bottom:1px solid #000000 !important; border-top:1px solid #000000 !important; border-left:1px solid #000000 !important; border-right:1px solid #000000 !important; color:#000000; font-family:'Arial'; font-size:10pt; background-color:#FBD4B4 }
	  td.style62 { vertical-align:middle; text-align:right; padding-right:0px; border-bottom:1px solid #000000 !important; border-top:1px solid #000000 !important; border-left:1px solid #000000 !important; border-right:1px solid #000000 !important; color:#000000; font-family:'Arial'; font-size:10pt; background-color:white }
	  td.style63 { vertical-align:middle; border-bottom:1px solid #000000 !important; border-top:1px solid #000000 !important; border-left:1px solid #000000 !important; border-right:1px solid #000000 !important; color:#000000; font-family:'Arial'; font-size:10pt; background-color:white }
	  td.style64 { vertical-align:middle; text-align:center; border-bottom:none #000000; border-top:none #000000; border-left:none #000000; border-right:none #000000; color:#000000; font-family:'Arial'; font-size:10pt; background-color:white }
	  td.style65 { vertical-align:middle; text-align:center; border-bottom:none #000000; border-top:none #000000; border-left:none #000000; border-right:none #000000; color:#000000; font-family:'Arial'; font-size:10pt; background-color:white }
	  td.style66 { vertical-align:middle; text-align:left; padding-left:0px; border-bottom:none #000000; border-top:none #000000; border-left:none #000000; border-right:none #000000; color:#000000; font-family:'Arial'; font-size:10pt; background-color:white }
	  td.style67 { vertical-align:middle; text-align:center; border-bottom:1px solid #000000 !important; border-top:1px solid #000000 !important; border-left:none #000000; border-right:1px solid #000000 !important; color:#000000; font-family:'Arial'; font-size:10pt; background-color:white }
	  td.style68 { vertical-align:middle; text-align:right; padding-right:0px; border-bottom:1px solid #000000 !important; border-top:1px solid #000000 !important; border-left:1px solid #000000 !important; border-right:1px solid #000000 !important; color:#000000; font-family:'Arial'; font-size:10pt; background-color:white }
	  td.style69 { vertical-align:middle; text-align:center; border-bottom:none #000000; border-top:none #000000; border-left:none #000000; border-right:none #000000; color:#000000; font-family:'Arial'; font-size:10pt; background-color:white }
	  td.style70 { vertical-align:bottom; text-align:center; border-bottom:none #000000; border-top:none #000000; border-left:none #000000; border-right:none #000000; color:#000000; font-family:'Arial'; font-size:10pt; background-color:white }
	  td.style71 { vertical-align:bottom; border-bottom:none #000000; border-top:none #000000; border-left:none #000000; border-right:none #000000; color:#000000; font-family:'Arial'; font-size:10pt; background-color:white }
	  
	  td.style152 { vertical-align:middle; text-align:center; border-bottom:none #000000; border-top:2px solid #000000; border-left:none #000000; border-right:none #000000; font-weight:bold; color:#000000; font-family:'Arial'; font-size:11pt; background-color:white }
	  td.style153 { vertical-align:middle; text-align:center; border-bottom:none #000000; border-top:none #000000; border-left:none #000000; border-right:none #000000; color:#000000; font-family:'돋움'; font-size:11pt; background-color:white }
	  td.style154 { vertical-align:middle; text-align:center; border-bottom:none #000000; border-top:none #000000; border-left:none #000000; border-right:none #000000; color:#000000; font-family:'Arial'; font-size:9pt; background-color:white }
	  
	  
	  table.sheet0 col.col0 { width:45.69999951pt }
	  table.sheet0 col.col1 { width:75.82222188pt }
	  table.sheet0 col.col2 { width:204.3333324pt }
	  table.sheet0 col.col3 { width:81.68888654pt }
	  table.sheet0 col.col4 { width:51.49999895pt }
	  table.sheet0 col.col5 { width:66.43333303pt }
	  table.sheet0 col.col6 { width:65.41111059pt }
	  table.sheet0 col.col7 { width:143.01110947pt }
	  table.sheet0 col.col8 { width:16.94444425pt }
	  table.sheet0 col.col9 { width:42.69999951pt }
	  table.sheet0 tr { height:15pt }
	  table.sheet0 tr.row0 { height:36pt }
	  table.sheet0 tr.row1 { height:15pt }
	  table.sheet0 tr.row2 { height:30pt }
	  table.sheet0 tr.row3 { height:15pt }
	  table.sheet0 tr.row4 { height:15pt }
	  table.sheet0 tr.row5 { height:15pt }
	  table.sheet0 tr.row6 { height:15pt }
	  table.sheet0 tr.row7 { height:15pt }
	  table.sheet0 tr.row8 { height:15pt }
	  table.sheet0 tr.row9 { height:15pt }
	  table.sheet0 tr.row10 { height:15pt }
	  table.sheet0 tr.row11 { height:15pt }
	  table.sheet0 tr.row12 { height:15pt }
	  table.sheet0 tr.row13 { height:15pt }
	  table.sheet0 tr.row14 { height:15pt }
	  table.sheet0 tr.row15 { height:15pt }
	  table.sheet0 tr.row16 { height:15pt }
	  table.sheet0 tr.row17 { height:15pt }
	  table.sheet0 tr.row18 { height:15pt }
	  table.sheet0 tr.row19 { height:15pt }
	  table.sheet0 tr.row20 { height:15pt }
	  table.sheet0 tr.row21 { height:15pt }
	  table.sheet0 tr.row22 { height:15pt }
	  table.sheet0 tr.row23 { height:15pt }
	  table.sheet0 tr.row24 { height:15pt }
	  table.sheet0 tr.row25 { height:15pt }
	  table.sheet0 tr.row26 { height:15pt }
	  table.sheet0 tr.row27 { height:15pt }
	  table.sheet0 tr.row28 { height:15pt }
	  table.sheet0 tr.row29 { height:15pt }
	  table.sheet0 tr.row30 { height:15pt }
	  table.sheet0 tr.row31 { height:15pt }
	  table.sheet0 tr.row32 { height:15pt }
	  table.sheet0 tr.row33 { height:15pt }
	  table.sheet0 tr.row34 { height:15pt }
	  table.sheet0 tr.row35 { height:15pt }
	  table.sheet0 tr.row36 { height:15pt }
	  table.sheet0 tr.row37 { height:15pt }
	  table.sheet0 tr.row38 { height:15pt }
	  table.sheet0 tr.row39 { height:15pt }
	  table.sheet0 tr.row41 { height:15pt }
	  table.sheet0 tr.row42 { height:15pt }
	  table.sheet0 tr.row43 { height:15pt }
	  table.sheet0 tr.row44 { height:15pt }
	  table.sheet0 tr.row45 { height:15pt }
	  table.sheet0 tr.row46 { height:15pt }
	  table.sheet0 tr.row47 { height:15pt }
	  table.sheet0 tr.row48 { height:15pt }
	  table.sheet0 tr.row49 { height:15pt }
	  table.sheet0 tr.row50 { height:15pt }
	  table.sheet0 tr.row51 { height:15pt }
	  table.sheet0 tr.row52 { height:15pt }
	  table.sheet0 tr.row53 { height:15pt }
	  table.sheet0 tr.row54 { height:15pt }
	  table.sheet0 tr.row55 { height:15pt }
	  table.sheet0 tr.row56 { height:15pt }
	  table.sheet0 tr.row57 { height:15pt }
	  table.sheet0 tr.row58 { height:15pt }
	  table.sheet0 tr.row59 { height:15pt }
	  table.sheet0 tr.row60 { height:15pt }
	  table.sheet0 tr.row61 { height:15pt }
	  table.sheet0 tr.row62 { height:15pt }
	  table.sheet0 tr.row63 { height:15pt }
	  table.sheet0 tr.row64 { height:15pt }
	  table.sheet0 tr.row65 { height:15pt }
	  table.sheet0 tr.row66 { height:15pt }
	  table.sheet0 tr.row67 { height:15pt }
	  table.sheet0 tr.row68 { height:15pt }
	  table.sheet0 tr.row69 { height:15pt }
	  table.sheet0 tr.row70 { height:15pt }
	  table.sheet0 tr.row71 { height:15pt }
	  table.sheet0 tr.row72 { height:15pt }
	  table.sheet0 tr.row73 { height:15pt }
	  table.sheet0 tr.row74 { height:15pt }
	  table.sheet0 tr.row75 { height:15pt }
	  table.sheet0 tr.row76 { height:15pt }
	  table.sheet0 tr.row77 { height:15pt }
	  table.sheet0 tr.row78 { height:15pt }
	  table.sheet0 tr.row79 { height:15pt }
	  table.sheet0 tr.row80 { height:15pt }
	  table.sheet0 tr.row81 { height:15pt }
	  table.sheet0 tr.row82 { height:15pt }
	  table.sheet0 tr.row83 { height:15pt }
	  table.sheet0 tr.row84 { height:15pt }
	  table.sheet0 tr.row85 { height:15pt }
	  table.sheet0 tr.row86 { height:15pt }
	  table.sheet0 tr.row87 { height:15pt }
	  table.sheet0 tr.row88 { height:15pt }
	  table.sheet0 tr.row89 { height:15pt }
	  table.sheet0 tr.row90 { height:15pt }
	  table.sheet0 tr.row91 { height:15.75pt }
	  table.sheet0 tr.row92 { height:15pt }
	  table.sheet0 tr.row93 { height:15pt }
	  table.sheet0 tr.row94 { height:15pt }
	  table.sheet0 tr.row95 { height:15pt }
	  table.sheet0 tr.row96 { height:15pt }
	  table.sheet0 tr.row97 { height:15pt }
	  table.sheet0 tr.row98 { height:15pt }
	  table.sheet0 tr.row99 { height:15pt }
	  table.sheet0 tr.row100 { height:15pt }
	  table.sheet0 tr.row101 { height:15pt }
	  table.sheet0 tr.row102 { height:15pt }
	  table.sheet0 tr.row103 { height:15pt }
	  table.sheet0 tr.row104 { height:15pt }
	  table.sheet0 tr.row105 { height:15pt }
	  table.sheet0 tr.row106 { height:15pt }
	  table.sheet0 tr.row107 { height:15pt }
	  table.sheet0 tr.row108 { height:15pt }
	  table.sheet0 tr.row109 { height:15pt }
	  table.sheet0 tr.row110 { height:15pt }
	  table.sheet0 tr.row111 { height:15pt }
	  table.sheet0 tr.row112 { height:15pt }
	  table.sheet0 tr.row113 { height:15pt }
	  table.sheet0 tr.row114 { height:15pt }
	  table.sheet0 tr.row115 { height:15pt }
	  table.sheet0 tr.row116 { height:15pt }
	  table.sheet0 tr.row117 { height:15pt }
	  table.sheet0 tr.row118 { height:15pt }
	  table.sheet0 tr.row119 { height:15pt }
	  table.sheet0 tr.row120 { height:15pt }
	  table.sheet0 tr.row121 { height:15pt }
	  table.sheet0 tr.row122 { height:15pt }
	  table.sheet0 tr.row123 { height:15pt }
	  table.sheet0 tr.row124 { height:15pt }
	  table.sheet0 tr.row125 { height:15pt }
	  table.sheet0 tr.row126 { height:15pt }
	  table.sheet0 tr.row128 { height:15pt }
	  table.sheet0 tr.row130 { height:15pt }
	  table.sheet0 tr.row131 { height:15pt }
	  table.sheet0 tr.row132 { height:15pt }
	  table.sheet0 tr.row133 { height:15pt }
	  table.sheet0 tr.row134 { height:15pt }
	  table.sheet0 tr.row135 { height:15pt }
	  table.sheet0 tr.row136 { height:15pt }
	  table.sheet0 tr.row137 { height:15pt }
	  table.sheet0 tr.row138 { height:15pt }
	  table.sheet0 tr.row139 { height:15pt }
	  table.sheet0 tr.row140 { height:15pt }
	  table.sheet0 tr.row141 { height:15pt }
	  table.sheet0 tr.row143 { height:15pt }
	  table.sheet0 tr.row146 { height:15pt }
	  table.sheet0 tr.row150 { height:15pt }
	  table.sheet0 tr.row152 { height:15pt }
	  table.sheet0 tr.row153 { height:15pt }
	  table.sheet0 tr.row154 { height:15pt }
	  table.sheet0 tr.row158 { height:15pt }
	  table.sheet0 tr.row159 { height:15pt }
	  table.sheet0 tr.row160 { height:15pt }
	  table.sheet0 tr.row161 { height:15pt }
	  table.sheet0 tr.row162 { height:15pt }
	  table.sheet0 tr.row163 { height:15pt }
	  table.sheet0 tr.row164 { height:15pt }
	  table.sheet0 tr.row165 { height:15pt }
	  table.sheet0 tr.row166 { height:15pt }
	  table.sheet0 tr.row167 { height:15pt }
	  table.sheet0 tr.row168 { height:15pt }
	  table.sheet0 tr.row169 { height:15pt }
	  table.sheet0 tr.row170 { height:15pt }
	  table.sheet0 tr.row171 { height:15pt }
	  table.sheet0 tr.row172 { height:15pt }
	  table.sheet0 tr.row173 { height:15pt }
	  table.sheet0 tr.row174 { height:15pt }
	  table.sheet0 tr.row175 { height:15pt }
	  table.sheet0 tr.row176 { height:15pt }
	  table.sheet0 tr.row177 { height:15pt }
	  table.sheet0 tr.row178 { height:15pt }
	  table.sheet0 tr.row179 { height:15pt }
	  table.sheet0 tr.row180 { height:15pt }
	  table.sheet0 tr.row181 { height:15pt }
	  table.sheet0 tr.row184 { height:15pt }
	  table.sheet0 tr.row185 { height:15pt }
	  table.sheet0 tr.row186 { height:15pt }
	  table.sheet0 tr.row187 { height:15pt }
	  table.sheet0 tr.row188 { height:15pt }
	  table.sheet0 tr.row189 { height:15pt }
	  table.sheet0 tr.row190 { height:15pt }
	  table.sheet0 tr.row191 { height:15pt }
	  table.sheet0 tr.row192 { height:15pt }
	  table.sheet0 tr.row193 { height:15pt }
	  table.sheet0 tr.row194 { height:15pt }
	  table.sheet0 tr.row195 { height:15pt }
	  table.sheet0 tr.row196 { height:15pt }
	  table.sheet0 tr.row197 { height:15pt }
	  table.sheet0 tr.row198 { height:15pt }
	  table.sheet0 tr.row199 { height:15pt }
	  table.sheet0 tr.row200 { height:15pt }
	  table.sheet0 tr.row201 { height:15pt }
	  table.sheet0 tr.row202 { height:15pt }
	  table.sheet0 tr.row203 { height:15pt }
	  table.sheet0 tr.row204 { height:15pt }
	  table.sheet0 tr.row205 { height:15pt }
	  table.sheet0 tr.row206 { height:15pt }
	  table.sheet0 tr.row207 { height:15pt }
	  table.sheet0 tr.row208 { height:15pt }
	  table.sheet0 tr.row209 { height:15pt }
	  table.sheet0 tr.row210 { height:15pt }
	  table.sheet0 tr.row211 { height:15pt }
	  table.sheet0 tr.row212 { height:15pt }
	  table.sheet0 tr.row213 { height:14.25pt }
	  table.sheet0 tr.row218 { height:14.25pt }
	  table.sheet0 tr.row222 { height:14.25pt }
	  table.sheet0 tr.row242 { height:15pt }
	  table.sheet0 tr.row243 { height:15pt }
	  table.sheet0 tr.row244 { height:15pt }
	  table.sheet0 tr.row245 { height:15pt }
	  table.sheet0 tr.row246 { height:15pt }
	  table.sheet0 tr.row247 { height:15pt }
	  table.sheet0 tr.row248 { height:15pt }
	  table.sheet0 tr.row249 { height:14.25pt }
	  table.sheet0 tr.row250 { height:14.25pt }
	  table.sheet0 tr.row251 { height:15pt }
	  table.sheet0 tr.row252 { height:15pt }
	  table.sheet0 tr.row253 { height:15pt }
	  table.sheet0 tr.row254 { height:15pt }
	  table.sheet0 tr.row255 { height:15pt }
	  table.sheet0 tr.row256 { height:14.25pt }
	  table.sheet0 tr.row258 { height:14.25pt }
	  table.sheet0 tr.row268 { height:14.25pt }
	  table.sheet0 tr.row271 { height:15pt }
	  table.sheet0 tr.row272 { height:30pt }
	  table.sheet0 tr.row273 { height:15pt }
	  table.sheet0 tr.row274 { height:15pt }
	  table.sheet0 tr.row275 { height:15pt }
	  table.sheet0 tr.row276 { height:15pt }
	  table.sheet0 tr.row277 { height:15pt }
	  table.sheet0 tr.row278 { height:15pt }
	  table.sheet0 tr.row279 { height:15pt }
	  table.sheet0 tr.row280 { height:15pt }
	  table.sheet0 tr.row281 { height:15pt }
	</style>
  </head>

  <body>
<style>
@page { left-margin: 0.43307086614173in; right-margin: 0.39370078740157in; top-margin: 0.98425196850394in; bottom-margin: 0.86614173228346in; }
body { left-margin: 0.43307086614173in; right-margin: 0.39370078740157in; top-margin: 0.98425196850394in; bottom-margin: 0.86614173228346in; }
</style>
	<table border="0" cellpadding="0" cellspacing="0" id="sheet0" class="sheet0">
		<col class="col0">
		<col class="col1">
		<col class="col2">
		<col class="col3">
		<col class="col4">
		<col class="col5">
		<col class="col6">
		<col class="col7">
		<col class="col8">
		<col class="col9">
		<tbody>
		  <tr class="row0">
			<td class="column1 style1 s" colspan="8">SB1100 Spare Parts Order Confirmation (Ver.2014.03.14)</td>
		  </tr>
		  <tr class="row1">
			<td class="column1 " colspan=8>P/I NO. : PI-14AG0001, &nbsp;&nbsp;&nbsp;&nbsp;Dest Country : Angola</td>
		  </tr>
		
				  
		  <tr class="row2">
			<td class="column0 style9 s">Model</td>
			<td class="column2 style10 s">CODE</td>
			<td class="column3 style11 s">Part name</td>
			<td class="column4 style10 s">@Price(EXW)</td>
			<td class="column5 style12 s">Q'ty</td>
			<td class="column6 style13 s">Amount</td>
			<td class="column7 style10 s">Unit Weight</td>
			<td class="column8 style10 s">Remark</td>
			
		  </tr>
		  <tr class="row3">
			<td class="column0 style15 s">SB-1100</td>
			<td class="column2 style15 s">1A01X3061A</td>
			<td class="column3 style16 s">ASS`Y_BRAKE_2</td>
			<td class="column4 style17 n">$ 46.00</td>
			<td class="column5 style17 n">&nbsp;1</td>
			<td class="column6 style17 n">$ 46</td>
			<td class="column7 style17 n">&nbsp;22.0 Kg</td>
			<td class="column8 style10 s">&nbsp;</td>
		  </tr>


		  <tr class="row260">
			<td class="column0 style15 s">SB-1100</td>
			<td class="column2 style15 s">7000B045XA</td>
			<td class="column3 style16 s">POWER_CORD_220V</td>
			<td class="column4 style17 n">$ 5.00</td>
			<td class="column5 style17 n">&nbsp;2</td>
			<td class="column6 style17 n">$ 10</td>
			<td class="column7 style19 null">&nbsp;</td>
			<td class="column8 style10 s">&nbsp;</td>
		  </tr>
		  <tr class="row261">
			<td class="column0 style15 s">SB-1100</td>
			<td class="column2 style15 s">7000C046XA</td>
			<td class="column3 style16 s">SERIAL_CABLE</td>
			<td class="column4 style17 n">$ 3.50</td>
			<td class="column5 style17 n">&nbsp;2</td>
			<td class="column6 style17 n">$ 7</td>
			<td class="column7 style17 n">&nbsp;</td>
			<td class="column8 style10 s">&nbsp;</td>
		  </tr>
		  <tr class="row262">
			<td class="column0 style15 s">SB-1100</td>
			<td class="column2 style15 s">1A00X2038A</td>
			<td class="column3 style16 s">ASS'Y_SEPARATOR</td>
			<td class="column4 style17 n">$ 65.00</td>
			<td class="column5 style17 n">&nbsp;1</td>
			<td class="column6 style17 n">$ 65.00</td>
			<td class="column7 style19 null">&nbsp;</td>
			<td class="column8 style10 s">Included SHAFT_HINGE_TOP</td>
		  </tr>
		  <tr class="row269">
			<td class="column0">&nbsp;</td>
			<td class="column2 style49 null"></td>
			<td class="column3 style50 null"></td>
			<td class="column4 style51 null"></td>
			<td class="column5 style52 null"></td>
			<td class="column6 style53 null"></td>
			<td class="column7 style52 null"></td>
			<td class="column8">&nbsp;</td>
		  </tr>
		  <tr class="row280">
			<td class="column0">&nbsp;</td>
			<td class="column2 style11 s" colspan=2>GRAND TOTAL</td>
			<td class="column4 style17 n">$ 129.50</td>
			<td class="column5 style68 f">6</td>
			<td class="column6 style63 f">$ 138.00</td>
			<td class="column7 style63 f">22.0 Kg</td>
			<td class="column8">&nbsp;</td>
		  </tr>
		  <tr class="row270">
			<td class="column0">&nbsp;</td>
			<td class="column2">&nbsp;</td>
			<td class="column3">&nbsp;</td>
			<td class="column4">&nbsp;</td>
			<td class="column5">&nbsp;</td>
			<td class="column6">&nbsp;</td>
			<td class="column7">&nbsp;</td>
			<td class="column8">&nbsp;</td>
		  </tr>
		  <tr class="row271">
			<td class="column2 style54 s" colspan=8>To order other unlisted parts, please fill in the blank and send us. Codes will be filled by us when confirming the order.</td>
		  </tr>
		  <tr class="row272">
			<td class="column0 style10 s">MODEL</td>
			<td class="column2 style10 s">CODE</td>
			<td class="column3 style10 s">Part name</td>
			<td class="column5 style12 s">Q'ty</td>
			<td class="column6 style13 s" colspan=3>P/I NO or Destination</td>
			<td class="column8 style10 s" colspan=2>Remark</td>
		  </tr>
		  <tr class="row273">
			<td class="column0 style10 s">&nbsp;</td>
			<td class="column2 style9 null">&nbsp;</td>
			<td class="column3 style9 null">&nbsp;</td>
			<td class="column4 style17 null">&nbsp;</td>
			<td class="column5 style13 null" colspan=3>&nbsp;</td>
			<td class="column8 style10 s">&nbsp;</td>
		  </tr>
		  <tr class="row274">
			<td class="column0 style10 s">&nbsp;</td>
			<td class="column2 style9 null">&nbsp;</td>
			<td class="column3 style9 null">&nbsp;</td>
			<td class="column4 style17 null">&nbsp;</td>
			<td class="column5 style13 null" colspan=3>&nbsp;</td>
			<td class="column8 style10 s">&nbsp;</td>
		  </tr>
		  <tr class="row276">
			<td class="column0">&nbsp;</td>
			<td class="column2 style64 null"></td>
			<td class="column3 style65 null"></td>
			<td class="column4 style66 null"></td>
			<td class="column5 style56 null"></td>
			<td class="column6">&nbsp;</td>
			<td class="column7 style58 null"></td>
			<td class="column8">&nbsp;</td>
		  </tr>
		  <tr class="row279">
			<td class="column0">&nbsp;</td>
			<td class="column2 style64 null"></td>
			<td class="column3 style65 null"></td>
			<td class="column4 style66 null"></td>
			<td class="column5 style56 null"></td>
			<td class="column6">&nbsp;</td>
			<td class="column7 style58 null"></td>
			<td class="column8">&nbsp;</td>
		  </tr>
		  <tr class="row281">
			<td class="column0">&nbsp;</td>
			<td class="column2 style64 null"></td>
			<td class="column3 style64 null"></td>
			<td class="column4 style56 null"></td>
			<td class="column5">&nbsp;</td>
			<td class="column6">&nbsp;</td>
			<td class="column7 style58 null"></td>
			<td class="column8">&nbsp;</td>
		  </tr>
		  
		  <tr class="row51">
			<td class="column0 style152 s" colspan=10>SBM Co., Ltd.</td>
		  </tr>
		  <tr class="row52">
			<td class="column0 style154 s" colspan=20>6F, Hyunwoo Bld, 206, Anyang7-Dong, Manan-Gu, Anyang-City, Gyeonggi-Do, KOREA . 430-817</td>
		  </tr>
		  <tr class="row53">
			<td class="column0 style154 s" colspan=10>Tel: +82-31-429-0789    Fax: +82-31-429-3607</td>
		  </tr>
		  
		</tbody>
	</table>
  </body>
</html>
