<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">
<!-- Generated by PHPExcel - http://www.phpexcel.net -->
<html>
  <head>
	<title>PACKING LIST</title>
  	  <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
	  <meta name="author" content="com" />
	  <meta name="company" content="Microsoft Corporation" />
	<style type="text/css">
	  html { font-family:Calibri, Arial, Helvetica, sans-serif; font-size:11pt; background-color:white }
	  table { border-collapse:collapse; page-break-after:always }
	  .gridlines td { border:1px dotted black }
	  .b { text-align:center }
	  .e { text-align:center }
	  .f { text-align:right }
	  .inlineStr { text-align:left }
	  .n { text-align:right }
	  .s { text-align:left }
	  td.style01 { vertical-align:middle; border-bottom:none #000000; border-top:1px solid #000000 !important; border-left:none; border-right:none; color:#000000; font-family:'Arial'; font-size:11pt; background-color:white }
	  td.style02 { vertical-align:middle; border-bottom:none #000000; border-top:1px solid #000000 !important; border-left:1px solid #000000 !important; border-right:none; font-weight:bold; color:#000000; font-family:'Arial'; font-size:9pt; background-color:white }
	  td.style03 { vertical-align:middle; border-bottom:none #000000; border-top:1px solid #000000 !important; border-left:none; border-right:1px solid #000000 !important; color:#000000; font-family:'Arial'; font-size:9pt; background-color:white }
	  td.style04 { vertical-align:middle; text-align:center; border-bottom:none #000000; border-top:1px solid #000000 !important; border-left:1px dashed #000000 !important; border-right:none #000000; color:#000000; font-family:'Arial'; font-size:9pt; background-color:white }
	  td.style05 { vertical-align:middle; text-align:center; border-bottom:none #000000; border-top:1px solid #000000 !important; border-left:none #000000; border-right:1px dashed #000000 !important; color:#000000; font-family:'Arial'; font-size:9pt; background-color:white }
	  td.style06 { vertical-align:middle; border-bottom:none #000000; border-top:2px solid #000000 !important; border-left:2px solid #000000 !important; border-right:none #000000; color:#000000; font-family:'Arial'; font-size:9pt; background-color:white }
	  td.style07 { vertical-align:middle; border-bottom:none #000000; border-top:2px solid #000000 !important; border-left:none #000000; border-right:none #000000; color:#000000; font-family:'Arial'; font-size:9pt; background-color:white }
	  td.style08 { vertical-align:middle; border-bottom:none #000000; border-top:2px solid #000000 !important; border-left:1px solid #000000 !important; border-right:none #000000; font-weight:bold; color:#000000; font-family:'Arial'; font-size:9pt; background-color:white }
	  td.style09 { vertical-align:middle; border-bottom:none #000000; border-top:2px solid #000000 !important; border-left:none #000000; border-right:2px solid #000000 !important; color:#000000; font-family:'Arial'; font-size:9pt; background-color:white }
	  td.style00 { vertical-align:middle; text-align:left; border-bottom:none #000000; border-top:1px solid #000000 !important; border-left:none #000000; border-right:1px dashed #000000 !important; color:#000000; font-family:'Arial'; font-size:9pt; background-color:white }
	  td.style001 { vertical-align:middle; text-align:right; border-bottom:none #000000; border-top:1px solid #000000 !important; border-left:1px dashed #000000 !important; border-right:none #000000; font-weight:bold; color:#000000; font-family:'Arial'; font-size:9pt; background-color:white }
	  td.style002 { vertical-align:middle; border-bottom:none #000000; border-top:1px solid #000000 !important; border-left:2px solid #000000 !important; border-right:none #000000; font-weight:bold; color:#000000; font-family:'Arial'; font-size:9pt; background-color:white }
	  td.style003 { vertical-align:middle; border-bottom:none #000000; border-top:1px solid #000000 !important; border-left:none #000000; border-right:none #000000; font-weight:bold; color:#000000; font-family:'Arial'; font-size:9pt; background-color:white }
	  td.style0 { vertical-align:bottom; border-bottom:none #000000; border-top:none #000000; border-left:none #000000; border-right:none #000000; color:#000000; font-family:'돋움'; font-size:11pt; background-color:white }
	  td.style1 { vertical-align:middle; border-bottom:none #000000; border-top:none #000000; border-left:none #000000; border-right:none #000000; color:#000000; font-family:'Arial'; font-size:11pt; background-color:white }
	  td.style2 { vertical-align:middle; border-bottom:none #000000; border-top:none #000000; border-left:none #000000; border-right:none #000000; color:#000000; font-family:'Arial'; font-size:11pt; background-color:white }
	  td.style3 { vertical-align:middle; border-bottom:none #000000; border-top:1px solid #000000 !important; border-left:2px solid #000000 !important; border-right:none #000000; color:#000000; font-family:'Arial'; font-size:9pt; background-color:white }
	  td.style4 { vertical-align:middle; border-bottom:none #000000; border-top:2px solid #000000 !important; border-left:none #000000; border-right:none #000000; color:#000000; font-family:'Arial'; font-size:9pt; background-color:white }
	  td.style5 { vertical-align:middle; border-bottom:none #000000; border-top:1px solid #000000 !important; border-left:1px solid #000000 !important; border-right:none #000000; font-weight:bold; color:#000000; font-family:'Arial'; font-size:9pt; background-color:white }
	  td.style6 { vertical-align:middle; border-bottom:none #000000; border-top:1px solid #000000 !important; border-left:none #000000; border-right:none #000000; color:#000000; font-family:'Arial'; font-size:9pt; background-color:white }
	  td.style7 { vertical-align:middle; border-bottom:none #000000; border-top:1px solid #000000 !important; border-left:none #000000; border-right:2px solid #000000 !important; color:#000000; font-family:'Arial'; font-size:9pt; background-color:white }
	  td.style8 { vertical-align:middle; border-bottom:none #000000; border-top:none #000000; border-left:none #000000; border-right:none #000000; color:#000000; font-family:'Arial'; font-size:9pt; background-color:white }
	  td.style9 { vertical-align:middle; border-bottom:none #000000; border-top:none #000000; border-left:2px solid #000000 !important; border-right:none #000000; color:#000000; font-family:'Arial'; font-size:11pt; background-color:white }
	  td.style10 { vertical-align:middle; border-bottom:none #000000; border-top:none #000000; border-left:none #000000; border-right:none #000000; font-weight:bold; color:#000000; font-family:'Arial'; font-size:11pt; background-color:white }
	  td.style11 { vertical-align:middle; border-bottom:none #000000; border-top:none #000000; border-left:1px solid #000000 !important; border-right:none #000000; color:#000000; font-family:'Arial'; font-size:11pt; background-color:white }
	  td.style12 { vertical-align:middle; border-bottom:none #000000; border-top:none #000000; border-left:none #000000; border-right:none #000000; color:#000000; font-family:'Arial'; font-size:11pt; background-color:white }
	  td.style13 { vertical-align:middle; border-bottom:none #000000; border-top:none #000000; border-left:none #000000; border-right:2px solid #000000 !important; color:#000000; font-family:'Arial'; font-size:11pt; background-color:white }
	  td.style14 { vertical-align:middle; border-bottom:none #000000; border-top:none #000000; border-left:none #000000; border-right:none #000000; color:#000000; font-family:'Arial'; font-size:9pt; background-color:white }
	  td.style15 { vertical-align:middle; border-bottom:1px solid #000000 !important; border-top:none #000000; border-left:1px solid #000000 !important; border-right:none #000000; color:#000000; font-family:'Arial'; font-size:11pt; background-color:white }
	  td.style16 { vertical-align:middle; border-bottom:1px solid #000000 !important; border-top:none #000000; border-left:none #000000; border-right:none #000000; color:#000000; font-family:'Arial'; font-size:11pt; background-color:white }
	  td.style17 { vertical-align:middle; border-bottom:1px solid #000000 !important; border-top:none #000000; border-left:none #000000; border-right:none #000000; color:#000000; font-family:'Arial'; font-size:11pt; background-color:white }
	  td.style18 { vertical-align:middle; border-bottom:1px solid #000000 !important; border-top:none #000000; border-left:none #000000; border-right:2px solid #000000 !important; color:#000000; font-family:'Arial'; font-size:11pt; background-color:white }
	  td.style19 { vertical-align:middle; border-bottom:none #000000; border-top:none #000000; border-left:1px solid #000000 !important; border-right:none #000000; font-weight:bold; color:#000000; font-family:'Arial'; font-size:11pt; background-color:white }
	  td.style20 { vertical-align:middle; border-bottom:1px solid #000000 !important; border-top:none #000000; border-left:2px solid #000000 !important; border-right:none #000000; color:#000000; font-family:'Arial'; font-size:11pt; background-color:white }
	  td.style21 { vertical-align:middle; border-bottom:1px solid #000000 !important; border-top:none #000000; border-left:none #000000; border-right:none #000000; color:#000000; font-family:'Arial'; font-size:9pt; background-color:white }
	  td.style22 { vertical-align:middle; border-bottom:none #000000; border-top:1px solid #000000; border-left:2px solid #000000 !important; border-right:none #000000; color:#000000; font-family:'Arial'; font-size:9pt; background-color:white }
	  td.style23 { vertical-align:middle; border-bottom:none #000000; border-top:1px solid #000000 !important; border-left:1px solid #000000 !important; border-right:none #000000; font-weight:bold; color:#000000; font-family:'Arial'; font-size:9pt; background-color:white }
	  td.style24 { vertical-align:middle; border-bottom:none #000000; border-top:1px solid #000000 !important; border-left:none #000000; border-right:2px solid #000000; color:#000000; font-family:'Arial'; font-size:9pt; background-color:white }
	  td.style25 { vertical-align:middle; border-bottom:none #000000; border-top:1px solid #000000 !important; border-left:none #000000; border-right:none #000000; color:#000000; font-family:'Arial'; font-size:9pt; background-color:white }
	  td.style26 { vertical-align:middle; border-bottom:none #000000; border-top:none #000000; border-left:none #000000; border-right:none #000000; color:#000000; font-family:'Arial'; font-size:9pt; background-color:white }
	  td.style27 { vertical-align:middle; border-bottom:none #000000; border-top:none #000000; border-left:none #000000; border-right:2px solid #000000 !important; color:#000000; font-family:'Arial'; font-size:9pt; background-color:white }
	  td.style28 { vertical-align:middle; border-bottom:none #000000; border-top:none #000000; border-left:none #000000; border-right:none #000000; font-weight:bold; color:#000000; font-family:'Arial'; font-size:10pt; background-color:white }
	  td.style29 { vertical-align:middle; border-bottom:none #000000; border-top:none #000000; border-left:none #000000; border-right:none #000000; color:#000000; font-family:'Arial'; font-size:10pt; background-color:white }
	  td.style30 { vertical-align:middle; border-bottom:none #000000; border-top:none #000000; border-left:none #000000; border-right:none #000000; font-weight:bold; color:#000000; font-family:'Arial'; font-size:10pt; background-color:white }
	  td.style31 { vertical-align:bottom; text-align:left; padding-left:9px; border-bottom:none #000000; border-top:none #000000; border-left:1px solid #000000 !important; border-right:none #000000; font-weight:bold; color:#000000; font-family:'Arial'; font-size:10pt; background-color:white }
	  td.style32 { vertical-align:middle; border-bottom:none #000000; border-top:none #000000; border-left:none #000000; border-right:none #000000; color:#000000; font-family:'Arial'; font-size:10pt; background-color:white }
	  td.style33 { vertical-align:bottom; text-align:left; padding-left:9px; border-bottom:none #000000; border-top:none #000000; border-left:1px solid #000000 !important; border-right:none #000000; color:#000000; font-family:'Arial'; font-size:10pt; background-color:white }
	  td.style34 { vertical-align:middle; text-align:center; border-bottom:none #000000; border-top:none #000000; border-left:1px solid #000000 !important; border-right:none #000000; color:#000000; font-family:'Arial'; font-size:10pt; background-color:white }
	  td.style35 { vertical-align:middle; text-align:center; border-bottom:none #000000; border-top:none #000000; border-left:none #000000; border-right:none #000000; color:#000000; font-family:'Arial'; font-size:11pt; background-color:white }
	  td.style36 { vertical-align:middle; text-align:center; border-bottom:none #000000; border-top:none #000000; border-left:none #000000; border-right:none #000000; color:#000000; font-family:'Arial'; font-size:10pt; background-color:white }
	  td.style37 { vertical-align:middle; text-align:center; border-bottom:none #000000; border-top:none #000000; border-left:none #000000; border-right:2px solid #000000 !important; color:#000000; font-family:'Arial'; font-size:11pt; background-color:white }
	  td.style38 { vertical-align:middle; border-bottom:none #000000; border-top:none #000000; border-left:none #000000; border-right:none #000000; color:#000000; font-family:'Arial'; font-size:10pt; background-color:white }
	  td.style39 { vertical-align:middle; border-bottom:none #000000; border-top:none #000000; border-left:none #000000; border-right:none #000000; color:#000000; font-family:'Arial'; font-size:10pt; background-color:white }
	  td.style40 { vertical-align:middle; border-bottom:1px solid #000000 !important; border-top:none #000000; border-left:none #000000; border-right:none #000000; color:#000000; font-family:'Arial'; font-size:10pt; background-color:white }
	  td.style41 { vertical-align:middle; border-bottom:1px solid #000000 !important; border-top:none #000000; border-left:none #000000; border-right:none #000000; color:#000000; font-family:'Arial'; font-size:10pt; background-color:white }
	  td.style42 { vertical-align:bottom; text-align:left; padding-left:9px; border-bottom:1px solid #000000 !important; border-top:none #000000; border-left:1px solid #000000 !important; border-right:none #000000; color:#000000; font-family:'Arial'; font-size:10pt; background-color:white }
	  td.style43 { vertical-align:middle; border-bottom:none #000000; border-top:none #000000; border-left:1px solid #000000 !important; border-right:none #000000; font-weight:bold; color:#000000; font-family:'Arial'; font-size:9pt; background-color:white }
	  td.style44 { vertical-align:bottom; text-align:center; border-bottom:none #000000; border-top:none #000000; border-left:2px solid #000000 !important; border-right:none #000000; color:#000000; font-family:'Arial'; font-size:10pt; background-color:white }
	  td.style45 { vertical-align:middle; text-align:center; border-bottom:none #000000; border-top:none #000000; border-left:none #000000; border-right:none #000000; color:#000000; font-family:'Arial'; font-size:10pt; background-color:white }
	  td.style46 { vertical-align:middle; border-bottom:1px solid #000000 !important; border-top:none #000000; border-left:2px solid #000000 !important; border-right:none #000000; color:#000000; font-family:'Arial'; font-size:11pt; background-color:white }
	  td.style47 { vertical-align:middle; border-bottom:1px solid #000000 !important; border-top:none #000000; border-left:none #000000; border-right:none #000000; font-weight:bold; color:#000000; font-family:'Arial'; font-size:11pt; background-color:white }
	  td.style48 { vertical-align:middle; border-bottom:1px solid #000000 !important; border-top:none #000000; border-left:none #000000; border-right:1px solid #000000 !important; color:#000000; font-family:'Arial'; font-size:11pt; background-color:white }
	  td.style49 { vertical-align:top; border-bottom:1px solid #000000 !important; border-top:none #000000; border-left:2px solid #000000 !important; border-right:none #000000; font-weight:bold; color:#000000; font-family:'Arial'; font-size:9pt; background-color:white }
	  td.style50 { vertical-align:middle; border-bottom:1px solid #000000 !important; border-top:none #000000; border-left:none #000000; border-right:none #000000; color:#000000; font-family:'Arial'; font-size:9pt; background-color:white }
	  td.style51 { vertical-align:middle; border-bottom:1px solid #000000 !important; border-top:none #000000; border-left:1px solid #000000 !important; border-right:none #000000; color:#000000; font-family:'Arial'; font-size:9pt; background-color:white }
	  td.style52 { vertical-align:middle; border-bottom:1px solid #000000 !important; border-top:none #000000; border-left:none #000000; border-right:2px solid #000000 !important; color:#000000; font-family:'Arial'; font-size:9pt; background-color:white }
	  td.style53 { vertical-align:middle; border-bottom:none #000000; border-top:none #000000; border-left:2px solid #000000 !important; border-right:none #000000; font-weight:bold; color:#000000; font-family:'Arial'; font-size:9pt; background-color:white }
	  td.style54 { vertical-align:middle; border-bottom:none #000000; border-top:none #000000; border-left:none #000000; border-right:none #000000; color:#000000; font-family:'Arial'; font-size:9pt; background-color:white }
	  td.style55 { vertical-align:middle; border-bottom:1px solid #000000 !important; border-top:none #000000; border-left:none #000000; border-right:none #000000; color:#000000; font-family:'Arial'; font-size:10pt; background-color:white }
	  td.style56 { vertical-align:middle; text-align:right; padding-right:9px; border-bottom:1px solid #000000 !important; border-top:none #000000; border-left:none #000000; border-right:1px solid #000000 !important; color:#000000; font-family:'Arial'; font-size:10pt; background-color:white }
	  td.style57 { vertical-align:middle; border-bottom:none #000000; border-top:none #000000; border-left:none #000000; border-right:none #000000; font-weight:bold; color:#000000; font-family:'Arial'; font-size:11pt; background-color:white }
	  td.style58 { vertical-align:middle; border-bottom:none #000000; border-top:none #000000; border-left:2px solid #000000 !important; border-right:none #000000; font-weight:bold; color:#000000; font-family:'Arial'; font-size:10pt; background-color:white }
	  td.style59 { vertical-align:middle; border-bottom:none #000000; border-top:none #000000; border-left:1px solid #000000 !important; border-right:none #000000; font-weight:bold; color:#000000; font-family:'Arial'; font-size:10pt; background-color:white }
	  td.style60 { vertical-align:middle; border-bottom:none #000000; border-top:1px solid #000000 !important; border-left:none #000000; border-right:none #000000; color:#000000; font-family:'Arial'; font-size:10pt; background-color:white }
	  td.style61 { vertical-align:middle; border-bottom:none #000000; border-top:none #000000; border-left:none #000000; border-right:2px solid #000000 !important; color:#000000; font-family:'Arial'; font-size:10pt; background-color:white }
	  td.style62 { vertical-align:middle; border-bottom:none #000000; border-top:none #000000; border-left:none #000000; border-right:none #000000; color:#000000; font-family:'Arial'; font-size:10pt; background-color:white }
	  td.style63 { vertical-align:bottom; border-bottom:1px solid #000000 !important; border-top:none #000000; border-left:none #000000; border-right:none #000000; color:#000000; font-family:'Arial'; font-size:10pt; background-color:white }
	  td.style64 { vertical-align:middle; border-bottom:none #000000; border-top:none #000000; border-left:none #000000; border-right:none #000000; font-weight:bold; color:#000000; font-family:'Arial'; font-size:10pt; background-color:white }
	  td.style65 { vertical-align:middle; border-bottom:none #000000; border-top:1px solid #000000 !important; border-left:none #000000; border-right:1px dotted #000000 !important; color:#000000; font-family:'Arial'; font-size:9pt; background-color:white }
	  td.style66 { vertical-align:middle; border-bottom:none #000000; border-top:1px solid #000000 !important; border-left:none #000000; border-right:none #000000; font-weight:bold; color:#000000; font-family:'Arial'; font-size:9pt; background-color:white }
	  td.style67 { vertical-align:middle; border-bottom:none #000000; border-top:1px solid #000000 !important; border-left:none #000000; border-right:none #000000; color:#000000; font-family:'Arial'; font-size:11pt; background-color:white }
	  td.style68 { vertical-align:middle; border-bottom:none #000000; border-top:1px solid #000000 !important; border-left:none #000000; border-right:1px dotted #000000 !important; color:#000000; font-family:'Arial'; font-size:9pt; background-color:white }
	  td.style69 { vertical-align:middle; border-bottom:none #000000; border-top:none #000000; border-left:none #000000; border-right:1px dotted #000000 !important; color:#000000; font-family:'Arial'; font-size:11pt; background-color:white }
	  td.style70 { vertical-align:middle; border-bottom:none #000000; border-top:none #000000; border-left:1px dotted #000000 !important; border-right:none #000000; color:#000000; font-family:'Arial'; font-size:11pt; background-color:white }
	  td.style71 { vertical-align:middle; border-bottom:none #000000; border-top:none #000000; border-left:1px dashed #000000 !important; border-right:none #000000; color:#000000; font-family:'Arial'; font-size:11pt; background-color:white }
	  td.style72 { vertical-align:middle; border-bottom:none #000000; border-top:none #000000; border-left:none #000000; border-right:none #000000; color:#000000; font-family:'Arial'; font-size:10pt; background-color:white }
	  td.style73 { vertical-align:middle; border-bottom:none #000000; border-top:none #000000; border-left:none #000000; border-right:none #000000; color:#000000; font-family:'Arial'; font-size:10pt; background-color:white }
	  td.style74 { vertical-align:middle; text-align:left; padding-left:0px; border-bottom:none #000000; border-top:none #000000; border-left:none #000000; border-right:2px solid #000000 !important; color:#000000; font-family:'Arial'; font-size:10pt; background-color:white }
	  td.style75 { vertical-align:middle; text-align:center; border-bottom:none #000000; border-top:none #000000; border-left:none #000000; border-right:2px solid #000000 !important; color:#000000; font-family:'Arial'; font-size:11pt; background-color:white }
	  td.style76 { vertical-align:middle; border-bottom:none #000000; border-top:none #000000; border-left:none #000000; border-right:none #000000; color:#000000; font-family:'Arial'; font-size:10pt; background-color:white }
	  td.style77 { vertical-align:middle; text-align:left; padding-left:0px; border-bottom:none #000000; border-top:none #000000; border-left:none #000000; border-right:none #000000; color:#000000; font-family:'Arial'; font-size:10pt; background-color:#FFFFFF }
	  td.style78 { vertical-align:middle; text-align:left; padding-left:0px; border-bottom:none #000000; border-top:none #000000; border-left:none #000000; border-right:none #000000; color:#000000; font-family:'Arial'; font-size:10pt; background-color:white }
	  td.style79 { vertical-align:middle; text-align:left; padding-left:0px; border-bottom:none #000000; border-top:none #000000; border-left:none #000000; border-right:none #000000; color:#000000; font-family:'Arial'; font-size:10pt; background-color:#FFFFFF }
	  td.style80 { vertical-align:bottom; border-bottom:none #000000; border-top:none #000000; border-left:none #000000; border-right:none #000000; color:#000000; font-family:'Arial'; font-size:11pt; background-color:white }
	  td.style81 { vertical-align:middle; text-align:left; padding-left:18px; border-bottom:none #000000; border-top:none #000000; border-left:none #000000; border-right:none #000000; color:#000000; font-family:'Arial'; font-size:10pt; background-color:white }
	  td.style82 { vertical-align:bottom; border-bottom:none #000000; border-top:none #000000; border-left:none #000000; border-right:none #000000; color:#000000; font-family:'Arial'; font-size:10pt; background-color:white }
	  td.style83 { vertical-align:middle; text-align:left; padding-left:18px; border-bottom:none #000000; border-top:none #000000; border-left:none #000000; border-right:none #000000; color:#000000; font-family:'Arial'; font-size:10pt; background-color:white }
	  td.style84 { vertical-align:middle; text-align:right; padding-right:0px; border-bottom:none #000000; border-top:none #000000; border-left:none #000000; border-right:none #000000; color:#000000; font-family:'Arial'; font-size:10pt; background-color:white }
	  td.style85 { vertical-align:middle; text-align:left; padding-left:9px; border-bottom:none #000000; border-top:none #000000; border-left:none #000000; border-right:none #000000; color:#000000; font-family:'Arial'; font-size:10pt; background-color:white }
	  td.style86 { vertical-align:middle; text-align:center; border-bottom:none #000000; border-top:none #000000; border-left:none #000000; border-right:none #000000; color:#000000; font-family:'Arial'; font-size:10pt; background-color:#FFFFFF }
	  td.style87 { vertical-align:middle; text-align:right; padding-right:0px; border-bottom:none #000000; border-top:none #000000; border-left:none #000000; border-right:none #000000; color:#000000; font-family:'Arial'; font-size:10pt; background-color:white }
	  td.style88 { vertical-align:middle; text-align:left; padding-left:0px; border-bottom:none #000000; border-top:none #000000; border-left:none #000000; border-right:none #000000; font-weight:bold; color:#000000; font-family:'Arial'; font-size:10pt; background-color:white }
	  td.style89 { vertical-align:middle; border-bottom:none #000000; border-top:none #000000; border-left:none #000000; border-right:none #000000; font-style:italic; color:#000000; font-family:'Arial'; font-size:10pt; background-color:white }
	  td.style90 { vertical-align:middle; border-bottom:none #000000; border-top:none #000000; border-left:none #000000; border-right:none #000000; color:#000000; font-family:'Arial'; font-size:10pt; background-color:#FFFFFF }
	  td.style91 { vertical-align:middle; text-align:left; padding-left:0px; border-bottom:none #000000; border-top:none #000000; border-left:none #000000; border-right:none #000000; font-style:italic; color:#000000; font-family:'Arial'; font-size:10pt; background-color:#FFFFFF }
	  td.style92 { vertical-align:middle; text-align:left; padding-left:0px; border-bottom:none #000000; border-top:none #000000; border-left:none #000000; border-right:none #000000; font-style:italic; color:#000000; font-family:'Arial'; font-size:10pt; background-color:white }
	  td.style93 { vertical-align:bottom; border-bottom:none #000000; border-top:none #000000; border-left:none #000000; border-right:none #000000; color:#000000; font-family:'Arial'; font-size:12pt; background-color:white }
	  td.style94 { vertical-align:bottom; border-bottom:none #000000; border-top:none #000000; border-left:none #000000; border-right:none #000000; color:#000000; font-family:'Arial'; font-size:10pt; background-color:white }
	  td.style95 { vertical-align:middle; border-bottom:none #000000; border-top:none #000000; border-left:none #000000; border-right:none #000000; font-weight:bold; text-decoration:underline; font-style:italic; color:#000000; font-family:'Arial'; font-size:11pt; background-color:white }
	  td.style96 { vertical-align:middle; text-align:right; padding-right:0px; border-bottom:none #000000; border-top:none #000000; border-left:none #000000; border-right:none #000000; color:#000000; font-family:'Arial'; font-size:11pt; background-color:white }
	  td.style97 { vertical-align:middle; border-bottom:none #000000; border-top:1px solid #000000 !important; border-left:2px solid #000000 !important; border-right:none #000000; color:#000000; font-family:'Arial'; font-size:11pt; background-color:white }
	  td.style98 { vertical-align:middle; border-bottom:none #000000; border-top:1px solid #000000 !important; border-left:none #000000; border-right:none #000000; color:#000000; font-family:'Arial'; font-size:11pt; background-color:white }
	  td.style99 { vertical-align:middle; border-bottom:none #000000; border-top:1px solid #000000 !important; border-left:none #000000; border-right:none #000000; font-weight:bold; text-decoration:underline; font-style:italic; color:#000000; font-family:'Arial'; font-size:11pt; background-color:white }
	  td.style100 { vertical-align:middle; border-bottom:none #000000; border-top:1px solid #000000 !important; border-left:none #000000; border-right:none #000000; font-weight:bold; color:#000000; font-family:'Arial'; font-size:10pt; background-color:white }
	  td.style101 { vertical-align:middle; text-align:left; padding-left:0px; border-bottom:none #000000; border-top:1px solid #000000 !important; border-left:none #000000; border-right:none #000000; font-weight:bold; color:#000000; font-family:'Arial'; font-size:10pt; background-color:white }
	  td.style102 { vertical-align:middle; border-bottom:none #000000; border-top:1px solid #000000 !important; border-left:none #000000; border-right:none #000000; font-weight:bold; color:#000000; font-family:'Arial'; font-size:10pt; background-color:white }
	  td.style103 { vertical-align:middle; text-align:center; border-bottom:none #000000; border-top:1px solid #000000 !important; border-left:none #000000; border-right:2px solid #000000 !important; font-weight:bold; color:#000000; font-family:'Arial'; font-size:10pt; background-color:white }
	  td.style104 { vertical-align:middle; border-bottom:none #000000; border-top:none #000000; border-left:none #000000; border-right:none #000000; font-weight:bold; color:#000000; font-family:'Arial'; font-size:9pt; background-color:white }
	  td.style105 { vertical-align:middle; border-bottom:none #000000; border-top:none #000000; border-left:2px solid #000000 !important; border-right:none #000000; font-weight:bold; color:#000000; font-family:'Arial'; font-size:8pt; background-color:white }
	  td.style106 { vertical-align:middle; border-bottom:none #000000; border-top:none #000000; border-left:none #000000; border-right:none #000000; font-weight:bold; color:#000000; font-family:'Arial'; font-size:8pt; background-color:white }
	  td.style107 { vertical-align:middle; border-bottom:2px solid #000000 !important; border-top:none #000000; border-left:2px solid #000000 !important; border-right:none #000000; color:#000000; font-family:'Arial'; font-size:11pt; background-color:white }
	  td.style108 { vertical-align:middle; border-bottom:2px solid #000000 !important; border-top:none #000000; border-left:none #000000; border-right:none #000000; color:#000000; font-family:'Arial'; font-size:11pt; background-color:white }
	  td.style109 { vertical-align:middle; border-bottom:2px solid #000000 !important; border-top:none #000000; border-left:none #000000; border-right:2px solid #000000 !important; color:#000000; font-family:'Arial'; font-size:11pt; background-color:white }
	  td.style110 { vertical-align:middle; border-bottom:1px solid #000000 !important; border-top:none #000000; border-left:none #000000; border-right:none #000000; color:#000000; font-family:'Arial'; font-size:10pt; background-color:white }
	  td.style200 { vertical-align:middle; text-align:left; padding-left:0px; border-bottom:none #000000; border-top:none #000000; border-left:none #000000; border-right:none #000000; font-weight:bold; color:#000000; font-family:'Arial'; font-size:8pt; background-color:white }
	  td.style201 { vertical-align:middle; text-align:center; border-bottom:none #000000; border-top:none #000000; border-left:none #000000; border-right:none #000000; color:#000000; font-family:'Arial'; font-size:10pt; background-color:white }
	  td.style202 { vertical-align:middle; text-align:left; padding-left:0px; border-bottom:none #000000; border-top:none #000000; border-left:none #000000; border-right:none #000000; font-weight:bold; color:#000000; font-family:'Arial'; font-size:8pt; background-color:white }
	  td.style203 { vertical-align:middle; text-align:left; padding-left:0px; border-bottom:none #000000; border-top:none #000000; border-left:none #000000; border-right:none #000000; font-weight:bold; color:#000000; font-family:'Arial'; font-size:8pt; background-color:white }
	  td.style204 { vertical-align:middle; text-align:left; padding-left:0px; border-bottom:1px solid #000000 !important; border-top:none #000000; border-left:none #000000; border-right:none #000000; color:#000000; font-family:'Arial'; font-size:10pt; background-color:white }
	  td.style205 { vertical-align:middle; text-align:center; border-bottom:none #000000; border-top:1px solid #000000 !important; border-left:1px dashed #000000 !important; border-right:none #000000; font-weight:bold; color:#000000; font-family:'Arial'; font-size:9pt; background-color:white }
	  td.style206 { vertical-align:right; text-align:center; border-bottom:none #000000; border-top:1px solid #000000 !important; border-left:none #000000; border-right:none #000000; font-weight:bold; color:#000000; font-family:'Arial'; font-size:9pt; background-color:white }
	  td.style207 { vertical-align:middle; text-align:right; border-bottom:none #000000; border-top:1px solid #000000 !important; border-left:none #000000; border-right:1px dashed #000000 !important; color:#000000; font-family:'Arial'; font-size:9pt; background-color:white }
	  td.style208 { vertical-align:middle; text-align:center; border-bottom:none #000000; border-top:1px solid #000000 !important; border-left:1px dashed #000000 !important; border-right:none #000000; font-weight:bold; color:#000000; font-family:'Arial'; font-size:9pt; background-color:white }
	  td.style209 { vertical-align:middle; text-align:center; border-bottom:none #000000; border-top:1px solid #000000 !important; border-left:none #000000; border-right:none #000000; color:#000000; font-family:'Arial'; font-size:11pt; background-color:white }
	  td.style210 { vertical-align:middle; text-align:center; border-bottom:none #000000; border-top:1px solid #000000 !important; border-left:none #000000; border-right:1px dashed #000000 !important; color:#000000; font-family:'Arial'; font-size:11pt; background-color:white }
	  td.style211 { vertical-align:middle; text-align:center; border-bottom:none #000000; border-top:1px solid #000000 !important; border-left:none #000000; border-right:2px solid #000000 !important; font-weight:bold; color:#000000; font-family:'Arial'; font-size:9pt; background-color:white }
	  td.style212 { vertical-align:middle; text-align:right; padding-right:0px; border-bottom:1px solid #000000 !important; border-top:none #000000; border-left:none #000000; border-right:none #000000; color:#000000; font-family:'Arial'; font-size:9pt; background-color:white }
	  td.style213 { vertical-align:middle; text-align:center; border-bottom:none #000000; border-top:1px solid #000000 !important; border-left:none #000000; border-right:none #000000; font-weight:bold; color:#000000; font-family:'Arial'; font-size:9pt; background-color:#FFFFFF }
	  td.style214 { vertical-align:middle; text-align:right; padding-right:0px; border-bottom:none #000000; border-top:1px solid #000000 !important; border-left:none #000000; border-right:none #000000; color:#000000; font-family:'Arial'; font-size:11pt; background-color:white }
	  td.style215 { vertical-align:middle; text-align:right; padding-right:0px; border-bottom:none #000000; border-top:1px solid #000000 !important; border-left:none #000000; border-right:none #000000; color:#000000; font-family:'Arial'; font-size:11pt; background-color:white }
	  td.style216 { vertical-align:middle; text-align:center; border-bottom:none #000000; border-top:none #000000; border-left:none #000000; border-right:none #000000; font-weight:bold; color:#000000; font-family:'Arial'; font-size:14pt; background-color:white }
	  td.style217 { vertical-align:middle; text-align:left; padding-left:0px; border-bottom:none #000000; border-top:none #000000; border-left:none #000000; border-right:none #000000; color:#000000; font-family:'Arial'; font-size:10pt; background-color:white }
	  td.style218 { vertical-align:middle; text-align:left; padding-left:0px; border-bottom:1px solid #000000 !important; border-top:none #000000; border-left:none #000000; border-right:none #000000; color:#000000; font-family:'Arial'; font-size:10pt; background-color:white }
	  td.style219 { vertical-align:middle; text-align:center; border-bottom:none #000000; border-top:none #000000; border-left:none #000000; border-right:none #000000; font-style:italic; color:#000000; font-family:'Arial'; font-size:10pt; background-color:#FFFFFF }
	  td.style220 { vertical-align:middle; text-align:right; padding-right:0px; border-bottom:none #000000; border-top:none #000000; border-left:none #000000; border-right:none #000000; font-style:italic; color:#000000; font-family:'Arial'; font-size:10pt; background-color:white }
	  td.style221 { vertical-align:middle; text-align:center; border-bottom:none #000000; border-top:none #000000; border-left:none #000000; border-right:none #000000; color:#000000; font-family:'Arial'; font-size:9pt; background-color:white }
	  td.style222 { vertical-align:middle; text-align:right; padding-right:0px; border-bottom:none #000000; border-top:none #000000; border-left:none #000000; border-right:none #000000; color:#000000; font-family:'Arial'; font-size:10pt; background-color:white }
	  td.style223 { vertical-align:middle; text-align:center; border-bottom:none #000000; border-top:none #000000; border-left:none #000000; border-right:none #000000; color:#000000; font-family:'Arial'; font-size:10pt; background-color:#FFFFFF }
	  td.style224 { vertical-align:middle; text-align:right; padding-right:0px; border-bottom:none #000000; border-top:none #000000; border-left:none #000000; border-right:none #000000; color:#000000; font-family:'Arial'; font-size:10pt; background-color:white }
	  td.style225 { vertical-align:middle; text-align:center; border-bottom:none #000000; border-top:none #000000; border-left:none #000000; border-right:none #000000; font-weight:bold; color:#000000; font-family:'Arial'; font-size:14pt; background-color:white }
	</style>
  </head>

  <body>
<style>
@page { left-margin: 0.19685039370079in; right-margin: 0.19685039370079in; top-margin: 0.39370078740157in; bottom-margin: 0.2755905511811in; }
body { left-margin: 0.19685039370079in; right-margin: 0.19685039370079in; top-margin: 0.39370078740157in; bottom-margin: 0.2755905511811in; }
</style>

	<table border="0" cellpadding="0" cellspacing="0" id="sheet0" class="sheet0" style="width: 210mm;height: 290mm;" align=center>
		<col class="col0">
		<col class="col1">
		<col class="col2">
		<col class="col3">
		<col class="col4">
		<col class="col5">
		<col class="col6">
		<col class="col7">
		<col class="col8">
		<col class="col9">
		<col class="col10">
		<col class="col11">
		<col class="col12">
		<col class="col13">
		<col class="col14">
		<col class="col15">
		<col class="col16">
		<col class="col17">
		<col class="col18">
		<col class="col19">
		<col class="col20">
		<col class="col21">
		<col class="col22">
		<col class="col23">
		<col class="col24">
		<col class="col25">
		<col class="col26">
		<col class="col27">
		<col class="col28">
		<col class="col29">
		<col class="col30">
		<col class="col31">
		<col class="col32">
		<col class="col33">
		<col class="col34">
		<col class="col35">
		<col class="col36">
		<col class="col37">
		<col class="col38">
		<col class="col39">
		<col class="col40">
		<col class="col41">
		<col class="col42">
		<col class="col43">
		<col class="col44">
		<col class="col45">
		<col class="col46">
		<col class="col47">
		<tbody>
		  <tr class="row0">
			<td class="column0 style225 s style225" colspan="7">PACKING LIST</td>
			<td class="column43 style1 null"></td>
		  </tr>
		  <tr class="row1">
			<td class="column0 style06 s" colspan=2 width=10%>Shipper :</td>
			<td class="column23 style07 s" width=45%></td>
			<td colspan=2 class="column23 style08 s" width=20%>Invoice date and No.</td>
			<td class="column42 style09 null" colspan=3 width=25%></td>
		  </tr>
		  <tr class="row2">
			<td class="column0 style9 null" colspan=2 rowspan=4><img style="width: 75px; height: 25px;" src="@base_url/images/common/sbmlogo.jpeg" border="0" /></td>
			<td class="column5 style10 s" valign=top>SBM CO., LTD.</td>
			<td class="column23 style11 null"></td>
			<td class="column24 style1 s"  colspan=3>Invoice date : @txt_invoice_dt</td>
			<td class="column42 style13 null"></td>
		  </tr>
		  <tr class="row2">
			<td class="column23 style14 null">6F, Hyunwoo Bld, 206, Anyang-Dong</td>
			<td class="column23 style11 null"></td>
			<td class="column24 style1 s" colspan=3>Invoice No : SWI-@txt_invoice_no</td>
			<td class="column42 style13 null"></td>
		  </tr>
		  <tr class="row2">
			<td class="column23 style14 null">Manan-Gu, Anyang-City, Gyeonggi-Do</td>
			<td class="column23 style11 null"></td>
			<td class="column24 style1 s"></td>
			<td class="column31 style217 n style217"></td>
			<td class="column42 style13 null" colspan=2></td>
		  </tr>
		  <tr class="row2">
			<td class="column23 style14 null">430-817, KOREA</td>
			<td class="column23 style02 null"></td>
			<td class="column24 style01 s" colspan=1>&nbsp;&nbsp;&nbsp;&nbsp;PI no.:</td>
			<td class="column24 style01 s" colspan=2>PI-@txt_pi_no</td>
			<td class="column31 style01 s style13" colspan=1></td>
		  </tr>
		  <tr class="row1">
			<td class="column0 style3 s" colspan=2>Consignee :</td>
			<td class="column23 style6 s" width=25%></td>
			<td colspan=4 class="column23 style5 s">Buyer(if other than consignee)</td>
			<td class="column42 style7 null"></td>
		  </tr>
		  <tr class="row2">
			<td class="column0 style9 null" colspan=2 rowspan=5></td>
			<td class="column5 style28 s" valign=top>@csn_cmpy_nm</td>
			<td class="column23 style11 null"></td>
			<td class="column24 style1 s style13" colspan=4 rowspan=5>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;SAME AS CONSIGNEE</td>
		  </tr>
		  <tr class="row2">
			<td class="column23 style14 null">@csn_addr</td>
			<td class="column23 style11 null"></td>
		  </tr>
		  <tr class="row2">
			<td class="column23 style14 null">@cntry </td>
			<td class="column23 style11 null"></td>
		  </tr>
		  <tr class="row2">
			<td class="column23 style14 null">Tel : @csn_tel&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Fax : @csn_fax</td>
			<td class="column23 style11 null"></td>
		  </tr>
		  <tr class="row2">
			<td class="column23 style14 null">Attn: @csn_attn</td>
			<td class="column23 style11 null"></td>
		  </tr>
		  
		  <tr class="row1">
			<td class="column0 style002 s" colspan=2>Vessel/Flight</td>
			<td class="column23 style003 s" width=25%>Port of Loading :</td>
			<td colspan=3 class="column23 style5 s">Terms of delivery and payment</td>
			<td class="column42 style7 null" colspan=2></td>
		  </tr>
		  <tr class="row2">
			<td class="column0 style9 null" colspan=2></td>
			<td class="column5 style1 s">@txt_ship_port_atcd</td>
			<td class="column23 style15 null"></td>
			<td class="column24 style1 s" colspan=2>@inv_payment</td>
			<td class="column42 style13 null"></td>
		  </tr>
		  
		  <tr class="row1">
			<td class="column0 style002 s" colspan=2>Final Destination</td>
			<td class="column23 style6 s" width=25%></td>
			<td colspan=3 class="column23 style5 s">HS Code : </td>
			<td class="column42 style7 null" colspan=2></td>
		  </tr>
		  <tr class="row2">
			<td class="column0 style9 null" colspan=2></td>
			<td class="column5 style1 s">@destnt, @cntry</td>
			<td class="column23 style15 null"></td>
			<td class="column24 style1 s"></td>
			<td class="column24 style1 s"></td>
			<td class="column42 style13 null" colspan=2></td>
		  </tr>
		  
		  <tr>
			<td class="column0 style3 s"></td>
			<td class="column1 style66 s style05">Carton No.<br>C/No.</td>
			<td class="column4 style66 s style05">No.& kind of pkgs;Goods description</td>
			<td class="column25 style205 s" width=10%>Quantity</td>
			<td class="column30 style205 s">Net Weight</td>
			<td class="column36 style205 s">Gross Weight</td>
			<td class="column36 style205 s">Measure (mm)</td>
			<td class="column47 style13 null"></td>
			</tr>
		  <tr id="eqpDiv" style="display:@eqpDiv" class="row22">
			<td class="column0 style3 s"></td>
			<td class="column1 style54 s style05">@eqp_carton_no</td>
			<td class="column4 style00">@mdl_nm</td>
			<td class="column25 style54 s style207">@eqp_cartons Cartons</td>
			<td class="column30 style54 s style207">@eqp_net_wgt Kg&nbsp;&nbsp;&nbsp;&nbsp;</td>
			<td class="column36 style54 s style207 s">@eqp_gross_wgt Kg
			&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
			</td>
			<td class="column36 style205 s"></td>
			<td class="column47 style13 null"></td>
		  </tr>
		  <tr id="spareDiv" style="display:@spareDiv" class="row22">
			<td class="column0 style3 s"></td>
			<td class="column1 style54 s style05">@part_carton_no</td>
			<td class="column4 style54 s style00">Currency Discrimination Counter Spare Parts</td>
			<td class="column25 style54 s style207">@part_cartons Cartons</td>
			<td class="column30 style54 s style207">@part_net_wgt Kg&nbsp;&nbsp;&nbsp;&nbsp;</td>
			<td class="column36 style54 s style207">@part_gross_wgt Kg
			&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
			</td>
			<td class="column36 style205 s"></td>
			<td class="column47 style13 null"></td>
		  </tr>
		  <tr id="addonDiv" style="display:@addonDiv" class="row22">
			<td class="column0 style3 s"></td>
			<td class="column1 style54 s style05">@addon_carton_no</td>
			<td class="column4 style54 s style00">Addon - @addon</td>
			<td class="column25 style54 s style207">@addon_cartons Cartons</td>
			<td class="column30 style54 s style207">&nbsp;&nbsp;&nbsp;&nbsp;</td>
			<td class="column36 style54 s style207">@addon_gross_wgt Kg
			&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
			</td>
			<td class="column36 style205 s"></td>
			<td class="column47 style13 null"></td>
		  </tr>
		  <tr class="row22">
			<td class="column0 style3 s"></td>
			<td class="column1 style54 s style05"></td>
			<td class="column4 style66 s style05">TOTAL :</td>
			<td class="column25 style001 s">@tot_cartons Cartons</td>
			<td class="column30 style001 s">&nbsp;&nbsp;&nbsp;&nbsp;</td>
			<td class="column36 style001 s">@tot_gross_wgt Kg
			&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
			</td>
			<td class="column36 style205 s"></td>
			<td class="column47 style13 null"></td>
		  </tr>

		  <tr class="row46">
			<td class="column0 style53 s" colspan=7 height=50px></td>
			<td class="column42 style13 null"></td>
		  </tr>
		  <tr class="row46">
			<td class="column0 style53 s" rowspan=2 width=5%></td>
		  	<td class="column1 style10 s" colspan=2>SBM CO., LTD</td>
			<td class="column29 style14 null">signed by</td>
			<td class="column28 style14 null" rowspan=2 colspan=3><img style="width: 180px; height: 80px;" src="@base_url/images/common/sbmsign.jpeg" border="0" /></td>
			<td class="column42 style13 null"></td>
		  </tr>
		  <tr class="row46">
		  	<td colspan=5>6F, Hyunwoo Bld, 206, Anyang-Dong<BR>Manan-Gu, Anyang-City, Gyeonggi-Do<BR>430-817, KOREA
		  	Tel : +82-31-429-0789<BR>Fax : +82-31-429-3607
		  	</td>
			<td class="column42 style13 null"></td>
		  </tr>
		  <tr class="row46">
			<td class="column0 style107 s"></td>
		  	<td class="column1 style108 s" colspan=6></td>
			<td class="column42 style109 s"></td>
		  </tr>
		  
		</tbody>
	</table>
  </body>
</html>
		  